// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

#[allow(unused_imports)]
pub use nikaia_std::prelude::*;

async fn __nikaia_main() {
    let served = hyper_shim::serve_once(18080);
    println!("served: {}", served);
    let crossed = hyper_shim::across_a_thread("a String is Send");
    println!("crossed: {}", crossed);
}


// ADR-038 D4: the runtime is running before the program's first
// statement, so an operation inside it costs no thread wake-up. What
// starts is what `user_parallelism` allows (ADR-037 D2): the I/O
// worker always, a pool for user code only at `yes`.
fn main() {
    nikaia_std::abort::report_in_nikaia_terms(__NIKAIA_SITES);
    let nikaia_runtime = nikaia_std::rt::start(nikaia_std::rt::UserCode::Sequential);
    let outcome = nikaia_std::rt::exec::block_on(__nikaia_main());
    nikaia_runtime.finish();
    outcome
}


// ADR-044 D1: the generated line, and the `.nika` line it came from.
const __NIKAIA_SITES: &[nikaia_std::abort::Site] = &[
    (7, "/home/user/Nikaia/examples/foreign-runtime/serve/src/main.nika", 20),
    (8, "/home/user/Nikaia/examples/foreign-runtime/serve/src/main.nika", 21),
    (9, "/home/user/Nikaia/examples/foreign-runtime/serve/src/main.nika", 22),
    (10, "/home/user/Nikaia/examples/foreign-runtime/serve/src/main.nika", 24),
    (11, "/home/user/Nikaia/examples/foreign-runtime/serve/src/main.nika", 25),
];
