// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


#[allow(unused_imports)]
use nikaia_std::time;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Next {
    Immediate,
    Delay(time::Duration),
    Escalate,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Failures {
    pub last_uptime: time::Duration,
    pub consecutive: i64,
    pub since_first: time::Duration,
}

pub trait Restart {
    fn decide(&mut self, history: Failures) -> Next;
}

