// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Span {
    pub start: u32,
    pub end: u32,
}

impl Span {
    pub fn nowhere() -> Span { Span { start: 0, end: 0 } }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Spanned<T> {
    pub node: T,
    pub span: Span,
    pub doc: Option<String>,
}

impl<T> Spanned<T> {
    pub fn new(node: T, span: Span) -> Spanned<T> { Spanned { node, span, doc: None } }
    pub fn documented(node: T, span: Span, doc: Option<String>) -> Spanned<T> { Spanned { node, span, doc } }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Program {
    pub items: Vec<Spanned<Item>>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Item {
    Fn { name: Option<winnow_grammar::Symbol>, generics: Vec<GenericParam>, receiver: Option<Receiver>, args: Vec<FnArg>, config: Vec<ConfigParam>, spread: Option<winnow_grammar::Symbol>, ret_type: Option<Type>, body: Block, is_sync: bool, sync_by: Vec<winnow_grammar::Symbol>, is_public: bool, can_throw: bool },
    Enum { name: winnow_grammar::Symbol, variants: Vec<EnumVariant>, is_public: bool },
    Struct { name: winnow_grammar::Symbol, generics: Vec<GenericParam>, fields: Vec<FieldDef>, is_public: bool },
    Impl { trait_name: Option<winnow_grammar::Symbol>, target: Type, methods: Vec<Spanned<Item>> },
    Trait { name: winnow_grammar::Symbol, methods: Vec<Spanned<TraitMethod>>, is_public: bool },
    Extern { abi: String, declarations: Vec<Spanned<TraitMethod>>, opaque: Vec<Spanned<OpaqueType>> },
    Test { name: String, body: Block },
    Bench { name: String, body: Block },
    Grammar(GrammarDef),
    Comptime { name: winnow_grammar::Symbol, ty: Option<Type>, value: Expr, public: bool },
    Import { path: Vec<winnow_grammar::Symbol>, alias: Option<winnow_grammar::Symbol> },
}

#[derive(Debug, Clone, PartialEq)]
pub struct Block {
    pub stmts: Vec<Spanned<Stmt>>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Stmt {
    Let { names: Vec<winnow_grammar::Symbol>, mutable: bool, ty: Option<Type>, value: Expr },
    Comptime { name: winnow_grammar::Symbol, ty: Option<Type>, value: Expr },
    Assign { target: Expr, op: Option<BinaryOp>, value: Expr },
    For { bindings: Vec<winnow_grammar::Symbol>, iter: Expr, body: Block },
    While { cond: Expr, body: Block },
    Return(Option<Expr>),
    Break,
    Continue,
    Expr(Expr),
}

#[derive(Debug, Clone, PartialEq)]
pub enum Expr {
    LitInt { value: u64, negative: bool },
    Match { value: Box<Expr>, arms: Vec<MatchArm> },
    Range { start: Box<Expr>, end: Box<Expr>, inclusive: bool },
    Tuple(Vec<Expr>),
    ListLit { items: Vec<Expr>, at: u32 },
    LitStr { text: String, at: u32 },
    LitInterpolated(String),
    LitChar(String),
    LitBool(bool),
    LitNull,
    Variable(winnow_grammar::Symbol),
    Block(Block),
    Overlap(Block),
    Select(Vec<SelectArm>),
    If { cond: Box<Expr>, then_branch: Block, else_branch: Option<Block> },
    Call { func: Box<Expr>, args: Vec<Expr>, config: Vec<ConfigArg> },
    Spawn { body: Box<Expr>, is_move: bool },
    Dsl { target: winnow_grammar::Symbol, context: Option<winnow_grammar::Symbol>, content: String },
    Path(Vec<winnow_grammar::Symbol>),
    MethodCall { receiver: Box<Expr>, method: winnow_grammar::Symbol, args: Vec<Expr>, config: Vec<ConfigArg> },
    Field { base: Box<Expr>, name: winnow_grammar::Symbol },
    StructLit { name: winnow_grammar::Symbol, fields: Vec<FieldInit> },
    With { base: Box<Expr>, fields: Vec<FieldInit>, at: u32 },
    Closure { params: Vec<winnow_grammar::Symbol>, mutable: Vec<winnow_grammar::Symbol>, body: Block },
    Unary { op: UnaryOp, expr: Box<Expr> },
    Binary { op: BinaryOp, lhs: Box<Expr>, rhs: Box<Expr>, span: Span, grouped: bool },
    SafeField { base: Box<Expr>, name: winnow_grammar::Symbol },
    SafeMethod { receiver: Box<Expr>, method: winnow_grammar::Symbol, args: Vec<Expr>, config: Vec<ConfigArg> },
    Try(Box<Expr>),
    Throw(Box<Expr>),
    Return(Box<Option<Expr>>),
    Break,
    Continue,
    LitFloat(String),
    Index { base: Box<Expr>, index: Box<Expr> },
    Cast { expr: Box<Expr>, ty: Type },
    Coalesce { value: Box<Expr>, fallback: Box<Expr> },
    Asm { bindings: Vec<AsmBinding>, code: String },
    Unsafe(Block),
    TryCatch { expr: Box<Expr>, handler: Block },
}

#[derive(Debug, Clone, PartialEq)]
pub struct Type {
    pub name: winnow_grammar::Symbol,
    pub generics: Vec<Type>,
    pub is_view: bool,
    pub is_tuple: bool,
    pub is_nullable: bool,
    pub code: Box<Option<Code>>,
    pub count: Option<i64>,
    pub is_mut: bool,
    pub is_slice: bool,
    pub either: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ExternMember {
    Declared(Spanned<TraitMethod>),
    Opaque(Spanned<OpaqueType>),
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct OpaqueType {
    pub name: winnow_grammar::Symbol,
    pub released_by: winnow_grammar::Symbol,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Code {
    pub result: Box<Option<Type>>,
    pub is_sync: bool,
    pub can_throw: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct EnumVariant {
    pub name: winnow_grammar::Symbol,
    pub fields: VariantFields,
}

#[derive(Debug, Clone, PartialEq)]
pub enum VariantFields {
    Unit,
    Tuple(Vec<Type>),
    Named(Vec<FieldDef>),
}

#[derive(Debug, Clone, PartialEq)]
pub struct SelectArm {
    pub binding: Option<winnow_grammar::Symbol>,
    pub value: Expr,
    pub body: Block,
    pub at: u32,
}

#[derive(Debug, Clone, PartialEq)]
pub struct MatchArm {
    pub pattern: MatchPattern,
    pub guard: Option<Expr>,
    pub body: Expr,
}

#[derive(Debug, Clone, PartialEq)]
pub enum MatchPattern {
    Otherwise,
    Literal(Expr),
    Path(Vec<winnow_grammar::Symbol>),
    Tuple { path: Vec<winnow_grammar::Symbol>, parts: Vec<MatchPattern> },
    Named { path: Vec<winnow_grammar::Symbol>, bindings: Vec<winnow_grammar::Symbol>, rest: bool },
    Or(Vec<MatchPattern>),
    Range { start: Expr, end: Expr },
}

#[derive(Debug, Clone, PartialEq)]
pub struct GenericParam {
    pub name: winnow_grammar::Symbol,
    pub bounds: Vec<winnow_grammar::Symbol>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct TraitMethod {
    pub name: winnow_grammar::Symbol,
    pub generics: Vec<GenericParam>,
    pub receiver: Option<Receiver>,
    pub args: Vec<FnArg>,
    pub config: Vec<ConfigParam>,
    pub ret_type: Option<Type>,
    pub is_sync: bool,
    pub can_throw: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct FnArg {
    pub name: winnow_grammar::Symbol,
    pub ty: Type,
    pub mutable: bool,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ConfigArg {
    pub name: winnow_grammar::Symbol,
    pub value: Expr,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ConfigParam {
    pub name: winnow_grammar::Symbol,
    pub ty: Type,
    pub default: Expr,
}

#[derive(Debug, Clone, PartialEq)]
pub struct FieldDef {
    pub name: winnow_grammar::Symbol,
    pub ty: Type,
    pub is_public: bool,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct AsmBinding {
    pub alias: winnow_grammar::Symbol,
    pub direction: String,
    pub location: String,
    pub variable: winnow_grammar::Symbol,
}

#[derive(Debug, Clone, PartialEq)]
pub struct FieldInit {
    pub name: winnow_grammar::Symbol,
    pub value: Option<Expr>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnaryOp {
    Neg,
    Not,
    Ref,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BinaryOp {
    Add,
    Sub,
    Mul,
    Div,
    Rem,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    And,
    Or,
    BitAnd,
    BitOr,
    BitXor,
    Shl,
    Shr,
}

impl BinaryOp {
    pub fn is_bitwise(self) -> bool { matches!(self, BinaryOp::BitAnd | BinaryOp::BitOr | BinaryOp::BitXor | BinaryOp::Shl | BinaryOp::Shr) }
    pub fn is_comparison(self) -> bool { matches!(self, BinaryOp::Eq | BinaryOp::Ne | BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge) }
}

#[derive(Debug, Clone, PartialEq)]
pub struct GrammarDef {
    pub name: winnow_grammar::Symbol,
    pub rules: Vec<GrammarRule>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct GrammarRule {
    pub name: winnow_grammar::Symbol,
    pub is_public: bool,
    pub frame: Option<FrameAttr>,
    pub ret_type: Option<Type>,
    pub label: Option<String>,
    pub alts: Vec<GrammarAlt>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FrameAttr {
    pub boundary: Option<String>,
    pub unchecked: bool,
}

impl FrameAttr {
    pub fn bare() -> FrameAttr { FrameAttr { boundary: None, unchecked: false } }
}

#[derive(Debug, Clone, PartialEq)]
pub struct GrammarAlt {
    pub pattern: Spanned<Pattern>,
    pub action: Option<Block>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Pattern {
    Seq(Vec<Spanned<Pattern>>),
    Choice(Vec<Spanned<Pattern>>),
    Bind { name: winnow_grammar::Symbol, pat: Box<Spanned<Pattern>> },
    Literal(String),
    Ref { name: winnow_grammar::Symbol, generics: Vec<Type>, args: Vec<Spanned<Pattern>> },
    Repeat { pat: Box<Spanned<Pattern>>, rep: Repeat },
    Group(Box<Spanned<Pattern>>),
    Cut,
    Fold(FoldSpec),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Repeat {
    Star,
    Plus,
    Optional,
    Exactly(u32),
    AtLeast(u32),
    Between(u32, u32),
}

#[derive(Debug, Clone, PartialEq)]
pub struct FoldSpec {
    pub parallel: bool,
    pub rule: winnow_grammar::Symbol,
    pub init: Expr,
    pub step: Expr,
    pub merge: Option<Expr>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Receiver {
    pub is_ref: bool,
    pub is_mut: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct FnParams {
    pub receiver: Option<Receiver>,
    pub args: Vec<FnArg>,
    pub config: Vec<ConfigParam>,
    pub spread: Option<winnow_grammar::Symbol>,
}

impl FnParams {
    pub fn none() -> FnParams { FnParams { receiver: None, args: vec![], config: vec![], spread: None } }
}

#[derive(Debug, Clone, PartialEq)]
pub enum ConfigZone {
    Options(Vec<ConfigParam>),
    Spread(winnow_grammar::Symbol),
}

