// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


#[allow(unused_imports)]
use nikaia_std::collections;

const NOT_SENDABLE: [&str; 5] = ["Rc<", "rc::Rc<", "*const ", "*mut ", "NonNull<"];

const PASSES_THROUGH: [&str; 4] = ["Vec", "Option", "Box", "VecDeque"];

const PLAIN: [&str; 18] = ["bool", "char", "str", "i8", "i16", "i32", "i64", "i128", "isize", "u8", "u16", "u32", "u64", "u128", "usize", "f32", "f64", "()"];

const THREAD_SINKS: [&str; 15] = ["std::thread::spawn", "std::thread::Builder::spawn", "std::thread::scope", "thread::spawn", "thread::scope", "tokio::spawn", "tokio::task::spawn", "tokio::task::spawn_blocking", "tokio::task::spawn_local", "task::spawn_blocking", "rayon::spawn", "rayon::scope", "rayon::join", "async_std::task::spawn", "smol::spawn"];

pub fn crosses(fields: &Vec<String>) -> Crosses {
    if fields.is_empty() { return Crosses::Undecided; }
    for field in fields.iter() {
        for marker in NOT_SENDABLE.iter() {
            let marker = *marker;
            if field.contains(marker) { return Crosses::MayNot; }
        }
    }
    for field in fields.iter() { if !plainly_sendable(field) { return Crosses::Undecided; } }
    Crosses::May
}

pub fn plainly_sendable(written: &str) -> bool {
    let ty = written.trim();
    if ty.starts_with("&") { return false; }
    for wrapper in PASSES_THROUGH.iter() {
        let wrapper = *wrapper;
        let inner = generic_of(ty, wrapper);
        if inner.is_some() {
            for part in paths_split(nikaia_std::index::or(inner.as_deref(), || "")) { if !plainly_sendable(&part) { return false; } }
            return true;
        }
    }
    is_plain(ty) || ty == "String"
}

pub fn is_plain(name: &str) -> bool {
    for plain in PLAIN.iter() {
        let plain = *plain;
        if name == plain { return true; }
    }
    false
}

pub fn generic_of(written: &str, name: &str) -> Option<String> {
    let text = written.trim();
    if !text.starts_with(name) { return None; }
    let c: Vec<char> = nikaia_std::list::chars(text.chars());
    let n: Vec<char> = nikaia_std::list::chars(name.chars());
    let after = slice(&c, n.len() as i64, c.len() as i64);
    let rest = after.trim_start();
    if !rest.starts_with("<") || !rest.ends_with(">") { return None; }
    let r: Vec<char> = nikaia_std::list::chars(rest.chars());
    Some(slice(&r, 1, r.len() as i64 - 1))
}

pub fn bounds_send(text: &str) -> bool {
    let c: Vec<char> = nikaia_std::list::chars(text.chars());
    let mut start: i64 = 0;
    for at in 0..c.len() as i64 + 1 {
        let ends = at == c.len() as i64 || !((*nikaia_std::index::get(&c, nikaia_std::index::at(at))).is_alphanumeric() || *nikaia_std::index::get(&c, nikaia_std::index::at(at)) == '_');
        if ends {
            if slice(&c, start, at) == "Send" { return true; }
            start = at + 1;
        }
    }
    false
}

pub fn a_list(names: &Vec<String>, one: &str, many: &str) -> String {
    if names.is_empty() { return String::from(""); }
    let mut word = many.to_owned();
    if (names.len() as i64) == 1 { word = one.to_owned(); }
    let mut out = format!("{} ", word);
    for at in 0..names.len() as i64 {
        if at > 0 && at == names.len() as i64 - 1 { out.push_str(" and "); } else if at > 0 { out.push_str(", "); }
        let name = nikaia_std::index::get(&names, nikaia_std::index::at(at));
        let quoted = format!("`{}`", name);
        out.push_str(&quoted);
    }
    out
}

pub fn reaches_a_thread(from: &str, calls: &collections::BTreeMap<String, Vec<String>>) -> Option<Vec<String>> {
    let mut seen: collections::BTreeSet<String> = collections::BTreeSet::new();
    let mut queue: Vec<String> = vec![from.to_owned()];
    let mut ways: Vec<Vec<String>> = vec![vec![]];
    seen.insert(from.to_owned());
    let mut next: i64 = 0;
    while next < queue.len() as i64 {
        let at = (*nikaia_std::index::get(&queue, nikaia_std::index::at(next))).to_owned();
        let how = (*nikaia_std::index::get(&ways, nikaia_std::index::at(next))).to_owned();
        next += 1;
        for call in calls_of(&at, calls) {
            if is_a_sink(&call) {
                let mut path = how.to_owned();
                path.push(call.to_owned());
                return Some(path);
            }
            let inside = the_crates_own(&call, calls);
            if inside.is_none() { continue; }
            let own = nikaia_std::index::or(inside, || "".into());
            if seen.contains(&own) { continue; }
            seen.insert(own.to_owned());
            let mut way = how.to_owned();
            way.push(own.to_owned());
            queue.push(own);
            ways.push(way);
        }
    }
    None
}

pub fn the_crates_own(call: &str, calls: &collections::BTreeMap<String, Vec<String>>) -> Option<String> {
    if calls.contains_key(call) { return Some(call.to_owned()); }
    let ending = format!("::{}", call);
    let mut found: Option<String> = None;
    for (path, _) in calls.iter() {
        if path.ends_with(&ending) {
            if found.is_some() { return None; }
            found = Some(path.to_owned());
        }
    }
    found
}

fn calls_of(function: &str, calls: &collections::BTreeMap<String, Vec<String>>) -> Vec<String> {
    for (path, called) in calls.iter() { if path == function { return called.to_owned(); } }
    vec![]
}

fn is_a_sink(call: &str) -> bool {
    for sink in THREAD_SINKS.iter() {
        let sink = *sink;
        if call == sink { return true; }
    }
    false
}

fn paths_split(text: &str) -> Vec<String> {
    let __keep_frame = nikaia_std::tether::Keep::new();
    let c: Vec<char> = nikaia_std::list::chars(text.chars());
    let mut out: Vec<String> = vec![];
    let mut depth = 0;
    let mut start: i64 = 0;
    for at in 0..c.len() as i64 {
        let one = *nikaia_std::index::get(&c, nikaia_std::index::at(at));
        if one == '<' || one == '(' || one == '[' { depth += 1; } else if one == '>' || one == ')' || one == ']' { depth -= 1; } else if one == ',' && depth == 0 {
            let piece = __keep_frame.put(slice(&c, start, at));
            out.push(piece.trim().to_owned());
            start = at + 1;
        }
    }
    let last = __keep_frame.put(slice(&c, start, c.len() as i64));
    let rest = last.trim();
    if !rest.is_empty() { out.push(rest.to_owned()); }
    out
}

fn slice(c: &[char], from: i64, to: i64) -> String {
    let mut out: String = String::from("");
    for k in from..to { out.push(*nikaia_std::index::get(&c, nikaia_std::index::at(k))); }
    out
}

pub fn promise_lines(promises: &Vec<String>) -> Vec<String> {
    let mut out: Vec<String> = vec![];
    if promises.is_empty() { return out; }
    out.push(String::from("**This crate makes promises the toolchain cannot check** (ADR-193 D5). A tool"));
    out.push(String::from("can see that the promise was made; it cannot see whether it is true - which is"));
    out.push(String::from("the line between a rule the toolchain enforces and one it inherits:"));
    for promise in promises.iter() { out.push(format!("  {}", promise)); }
    out
}

pub fn thread_lines(name: &str, bound: &Vec<String>, way: Option<Vec<String>>) -> Vec<String> {
    let mut out: Vec<String> = vec![];
    if !bound.is_empty() {
        let listed = a_list(bound, "the parameter", "the parameters");
        out.push(format!("`{}`: {} is bound `Send`.", name, listed));
        out.push(String::from("  Seen and not claimed (ADR-193 D3): a `Send` bound says the callee **may**"));
        out.push(String::from("  send it, which is usually `spawn` and is sometimes an API keeping a door open."));
    }
    if way.is_some() {
        let steps = nikaia_std::index::or(way, || vec![].into());
        let sink = nikaia_std::index::get(&steps, nikaia_std::index::at(steps.len() as i64 - 1));
        if (steps.len() as i64) == 1 { out.push(format!("`{}`: calls `{}`.", name, sink)); } else {
            let mut through: String = String::from("");
            for at in 0..steps.len() as i64 - 1 {
                if at > 0 { through.push_str(" -> "); }
                let step = nikaia_std::index::get(&steps, nikaia_std::index::at(at));
                let quoted = format!("`{}`", step);
                through.push_str(&quoted);
            }
            out.push(format!("`{}`: reaches `{}` through {}.", name, sink, through));
        }
        out.push(String::from("  A sink reached through a call says *this function threads something*,"));
        out.push(String::from("  never *this function threads your argument* (ADR-193 D4) - connecting"));
        out.push(String::from("  those is dataflow through a closure capture and is not built."));
    }
    if out.is_empty() { return out; }
    out.push(String::from("  Does this put it on a thread?  -> threads = true | false"));
    out
}

pub fn type_entry(fields: &Vec<String>, derives: &collections::BTreeSet<String>) -> TypeContract {
    let mut entry = TypeContract::empty();
    entry.public = true;
    entry.crosses = crosses(fields);
    entry.compares = derives.contains("PartialEq");
    entry.copies = derives.contains("Copy");
    entry
}

