// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
pub fn parameters(body: &str) -> Vec<String> {
    let c: Vec<char> = body.chars().collect::<Vec<_>>();
    let mut found: Vec<String> = Vec::new();
    let mut i: i64 = 0;
    while i < c.len() as i64 {
        if *nikaia_std::index::get(&c, nikaia_std::index::at(i)) != ':' {
            i += 1;
            continue;
        }
        let before = i > 0 && *nikaia_std::index::get(&c, nikaia_std::index::at(i - 1)) == ':';
        let after = i + 1 < c.len() as i64 && *nikaia_std::index::get(&c, nikaia_std::index::at(i + 1)) == ':';
        if before || after {
            i += 2;
            continue;
        }
        let start: i64 = i + 1;
        let mut end: i64 = start;
        while end < c.len() as i64 && a_name_goes_on(*nikaia_std::index::get(&c, nikaia_std::index::at(end))) { end += 1; }
        if end > start && a_name_begins(*nikaia_std::index::get(&c, nikaia_std::index::at(start))) {
            let mut name: String = String::new();
            for k in start..end { name.push(*nikaia_std::index::get(&c, nikaia_std::index::at(k))); }
            if !found.contains(&name) { found.push(name); }
            i = end;
        } else { i += 1; }
    }
    found
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
fn a_name_goes_on(c: char) -> bool { matches!(c, 'a'..='z' | 'A'..='Z' | '0'..='9' | '_') }

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
fn a_name_begins(c: char) -> bool { matches!(c, 'a'..='z' | 'A'..='Z' | '_') }

