// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


pub const HASHED_FROM: i64 = 12;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Table {
    pub seed: u64,
    pub disps: Vec<(u32, u32)>,
    pub keys: Vec<String>,
    pub order: Vec<i64>,
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
pub fn fnv(key: &str, seed: u64) -> u64 {
    let mut hash: u64 = 14695981039346656037u64 ^ seed;
    for b in key.bytes() {
        hash ^= b as u64;
        hash = hash.wrapping_mul(1099511628211u64);
    }
    hash
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
pub fn displace(f1: u32, f2: u32, d1: u32, d2: u32) -> u32 { d2.wrapping_add(f1.wrapping_mul(d1)).wrapping_add(f2) }

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
pub fn build(keys: &[String]) -> Option<Table> {
    let n = keys.len() as i64;
    if n < HASHED_FROM {
        let mut written: Vec<String> = vec![];
        let mut order: Vec<i64> = vec![];
        for at in 0..n {
            written.push((*nikaia_std::index::get(&keys, nikaia_std::index::at(at))).to_owned());
            order.push(at);
        }
        return Some(Table { seed: 0, disps: vec![], keys: written, order });
    }
    let mut buckets = (n + 4) / 5;
    if buckets < 1 { buckets = 1; }
    for seed in 0..200 {
        let table = attempt(keys, seed as u64, buckets, n);
        if table.is_some() { return table; }
    }
    None
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
fn attempt(keys: &[String], seed: u64, buckets: i64, n: i64) -> Option<Table> {
    let mut by_bucket: Vec<Vec<(i64, u32, u32)>> = vec![];
    for _ in 0..buckets { by_bucket.push(vec![]); }
    for at in 0..n {
        let hash = fnv(nikaia_std::index::get(&keys, nikaia_std::index::at(at)), seed);
        let g = (hash >> 32) as u32;
        let f1 = hash as u32;
        let f2 = (hash >> 16) as u32;
        by_bucket[nikaia_std::index::at(g as i64 % buckets)].push((at, f1, f2));
    }
    let mut order: Vec<(i64, i64)> = vec![];
    for b in 0..buckets {
        let size = (*nikaia_std::index::get(&by_bucket, nikaia_std::index::at(b))).len() as i64;
        if size > 0 { order.push((0 - size, b)); }
    }
    order.sort();
    let mut disps: Vec<(u32, u32)> = vec![];
    for _ in 0..buckets { disps.push((0, 0)); }
    let mut slots: Vec<i64> = vec![];
    for _ in 0..n { slots.push(-1); }
    for (_, bucket) in order.iter() {
        let bucket = nikaia_std::num::value(bucket);
        let mut placed = false;
        let mut d1: u32 = 0u32;
        while !placed && (d1 as i64) < n {
            let mut d2: u32 = 0u32;
            while !placed && (d2 as i64) < n {
                let mut taken: Vec<(i64, i64)> = vec![];
                let mut fits = true;
                for (at, f1, f2) in (*nikaia_std::index::get(&by_bucket, nikaia_std::index::at(bucket))).iter() {
                    let at = nikaia_std::num::value(at);let f1 = nikaia_std::num::value(f1);let f2 = nikaia_std::num::value(f2);
                    let slot = displace(f1, f2, d1, d2) as i64 % n;
                    let mut clash = *nikaia_std::index::get(&slots, nikaia_std::index::at(slot)) >= 0;
                    for t in taken.iter() { if t.0 == slot { clash = true; } }
                    if clash {
                        fits = false;
                        break;
                    }
                    taken.push((slot, at));
                }
                if fits {
                    { let __nikaia_stored = (d1, d2); nikaia_std::index::set(&mut disps, nikaia_std::index::at(bucket), __nikaia_stored); }
                    for (slot, at) in taken.iter() {
                        let slot = nikaia_std::num::value(slot);let at = nikaia_std::num::value(at);
                        { let __nikaia_stored = at; nikaia_std::index::set(&mut slots, nikaia_std::index::at(slot), __nikaia_stored); }
                    }
                    placed = true;
                }
                d2 += 1;
            }
            d1 += 1;
        }
        if !placed { return None; }
    }
    let mut written: Vec<String> = vec![];
    let mut at_of: Vec<i64> = vec![];
    for slot in slots.iter() {
        let slot = nikaia_std::num::value(slot);
        if slot < 0 { return None; }
        written.push((*nikaia_std::index::get(&keys, nikaia_std::index::at(slot))).to_owned());
        at_of.push(slot);
    }
    Some(Table { seed, disps, keys: written, order: at_of })
}

