// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Constant {
    pub magnitude: u64,
    pub negative: bool,
    pub pinned: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Folded {
    Value(Constant),
    Overflows(Constant),
    TooLarge(bool),
    Nothing,
}

const I8_LOW: u64 = 128;

const I8_HIGH: u64 = 127;

const I16_LOW: u64 = 32768;

const I16_HIGH: u64 = 32767;

const I32_LOW: u64 = 2147483648;

const I32_HIGH: u64 = 2147483647;

const I64_LOW: u64 = 9223372036854775808;

const I64_HIGH: u64 = 9223372036854775807;

const U8_HIGH: u64 = 255;

const U16_HIGH: u64 = 65535;

const U32_HIGH: u64 = 4294967295;

const U64_HIGH: u64 = 18446744073709551615;

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
pub fn fits(c: &Constant, ty: &str) -> bool {
    let (low, high) = match ty {
        "i8" => (I8_LOW, I8_HIGH),
        "i16" => (I16_LOW, I16_HIGH),
        "i32" => (I32_LOW, I32_HIGH),
        "i64" => (I64_LOW, I64_HIGH),
        "u8" => (0, U8_HIGH),
        "u16" => (0, U16_HIGH),
        "u32" => (0, U32_HIGH),
        "u64" => (0, U64_HIGH),
        _ => return true,
    };
    if c.negative { return c.magnitude <= low; }
    c.magnitude <= high
}

fn number(magnitude: u64, negative: bool, pinned: String) -> Constant { Constant { magnitude, negative: negative && magnitude != 0u64, pinned } }

fn added(a: &Constant, b_magnitude: u64, b_negative: bool, pinned: String) -> Folded {
    if a.negative == b_negative {
        let sum = a.magnitude.wrapping_add(b_magnitude);
        if sum < a.magnitude { return Folded::TooLarge(a.negative); }
        return Folded::Value(number(sum, a.negative, pinned));
    }
    if a.magnitude >= b_magnitude { return Folded::Value(number(a.magnitude - b_magnitude, a.negative, pinned)); }
    Folded::Value(number(b_magnitude - a.magnitude, b_negative, pinned))
}

fn multiplied(a: &Constant, b: &Constant, pinned: String) -> Folded {
    let negative = a.negative != b.negative;
    if a.magnitude == 0u64 { return Folded::Value(number(0u64, false, pinned)); }
    let product = a.magnitude.wrapping_mul(b.magnitude);
    if product.wrapping_div(a.magnitude) != b.magnitude { return Folded::TooLarge(negative); }
    Folded::Value(number(product, negative, pinned))
}

pub fn constant_of(expr: &Expr, name_is: &impl Fn(winnow_grammar::Symbol) -> Folded) -> Folded {
    match expr {
        Expr::LitInt { value, negative } => { let negative = *negative; let value = *value; Folded::Value(number(value, negative, String::from(""))) },
        Expr::Variable(name) => { let name = *name; name_is(name) },
        Expr::Unary { op, expr } => { let expr = nikaia_std::boxed::open(expr); negated(op, expr, name_is) },
        Expr::Binary { op, lhs, rhs, .. } => { let lhs = nikaia_std::boxed::open(lhs); let rhs = nikaia_std::boxed::open(rhs); combined(op, lhs, rhs, name_is) },
        _ => Folded::Nothing,
    }
}

fn negated(op: &UnaryOp, inner: &Expr, name_is: &impl Fn(winnow_grammar::Symbol) -> Folded) -> Folded {
    match op {
        UnaryOp::Neg => { },
        _ => return Folded::Nothing,
    };
    match constant_of(inner, name_is) {
        Folded::Value(c) => pinned_step(number(c.magnitude, !c.negative, c.pinned)),
        Folded::TooLarge(negative) => Folded::TooLarge(!negative),
        other => other,
    }
}

fn pinned_step(c: Constant) -> Folded { if fits(&c, &c.pinned) { Folded::Value(c) } else { Folded::Overflows(c) } }

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
fn combined(op: &BinaryOp, lhs: &Expr, rhs: &Expr, name_is: &impl Fn(winnow_grammar::Symbol) -> Folded) -> Folded {
    let a = match constant_of(lhs, name_is) {
        Folded::Value(c) => c,
        other => return other,
    };
    let b = match constant_of(rhs, name_is) {
        Folded::Value(c) => c,
        other => return other,
    };
    if !a.pinned.is_empty() && !b.pinned.is_empty() && a.pinned != b.pinned { return Folded::Nothing; }
    let pinned = if a.pinned.is_empty() { b.pinned.clone() } else { a.pinned.clone() };
    let folded = match op {
        BinaryOp::Add => added(&a, b.magnitude, b.negative, pinned),
        BinaryOp::Sub => added(&a, b.magnitude, !b.negative, pinned),
        BinaryOp::Mul => multiplied(&a, &b, pinned),
        BinaryOp::Div => divided(&a, &b, pinned, false),
        BinaryOp::Rem => divided(&a, &b, pinned, true),
        _ => Folded::Nothing,
    };
    match folded {
        Folded::Value(c) => pinned_step(c),
        other => other,
    }
}

fn divided(a: &Constant, b: &Constant, pinned: String, remainder: bool) -> Folded {
    if b.magnitude == 0u64 { return Folded::Nothing; }
    if remainder { return Folded::Value(number(a.magnitude % b.magnitude, a.negative, pinned)); }
    Folded::Value(number(a.magnitude / b.magnitude, a.negative != b.negative, pinned))
}

pub fn wants_widening(folded: &Folded) -> bool {
    match folded {
        Folded::Value(c) => c.pinned.is_empty() && !fits(c, "i32") && fits(c, "i64"),
        _ => false,
    }
}

