// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

use winnow_grammar::grammar;

#[allow(unused_imports)]
use nikaia_std::text;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Field<'a> {
    pub name: &'a str,
    pub value: &'a str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Line<'a> {
    Field(Field<'a>),
    Skip,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Written<'a> {
    pub words: Vec<&'a str>,
    pub fields: Vec<Field<'a>>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Header<'a> {
    pub name: String,
    pub value: &'a str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Read<'a> {
    pub refused: &'a str,
    pub method: &'a str,
    pub target: &'a str,
    pub length: i64,
    pub keep_alive: bool,
    pub headers: Vec<Header<'a>>,
}

grammar! {
    grammar Http1 {

        rule WS =
            ""
            -> { }

        pub rule head -> Written<'a> =
            words:__nikaia_list<&'a str>(item = WORD, sep = " ") "\r\n" lines:line* "\r\n" eof
            -> { Written { words, fields: fields(lines) } }

        rule WORD -> &'a str =
            w:text(WORD_PIECE*)
            -> { w }

        rule WORD_PIECE =
            not(" ") not("\r\n") any
            -> { }

        rule line -> Line<'a> =
            n:text(NAME_PIECE*) ":" v:text(REST_PIECE*) "\r\n"
            -> { Line::Field(Field { name: n, value: v }) }
          | OTHER "\r\n"
            -> { Line::Skip }

        rule NAME_PIECE =
            not(":") not("\r\n") any
            -> { }

        rule REST_PIECE =
            not("\r\n") any
            -> { }

        rule OTHER =
            REST_PIECE+
            -> { }

        rule __nikaia_list<T>(item: Rule<T>, sep) -> Vec<T> =
          first:item rest:__nikaia_list_more<T>(item = item, sep = sep)*
            -> { let mut all = vec![first]; all.extend(rest); all }
        | ""
            -> { Vec::new() }

        rule __nikaia_list_more<T>(item: Rule<T>, sep) -> T =
          sep x:item
            -> { x }
    }
}

fn fields(lines: Vec<Line<'_>>) -> Vec<Field<'_>> {
    let mut all = Vec::new();
    for line in lines.into_iter() {
        match line {
            Line::Field(f) => { all.push(f) },
            Line::Skip => { },
        };
    }
    all
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
pub fn read<'a>(written: &Written<'a>) -> Read<'a> {
    if (written.words.len() as i64) < 3 { return refused("400 a request line that is not three words"); }
    let method = *nikaia_std::index::get(&written.words, 0);
    let target = *nikaia_std::index::get(&written.words, 1);
    if !(*nikaia_std::index::get(&written.words, 2)).starts_with("HTTP/1.") { return refused("400 a version this does not speak"); }
    if method != "GET" && method != "POST" { return refused("400 a method this does not answer"); }
    let mut length: i64 = 0;
    let mut keep_alive = false;
    let mut headers: Vec<Header<'_>> = vec![];
    for field in written.fields.iter() {
        let name = field.name.trim().to_lowercase();
        let value = field.value.trim();
        if name == "content-length" {
            let n = nikaia_std::index::or(text::parse_i64(value), || -1);
            if n < 0 { return refused("400 a content-length that is not a count"); }
            length = n;
        } else if name == "connection" { keep_alive = value.to_lowercase() == "keep-alive"; } else if name == "transfer-encoding" { return refused("400 a transfer-encoding this does not speak"); }
        headers.push(Header { name, value });
    }
    Read { refused: "", method, target, length, keep_alive, headers }
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
fn refused(why: &str) -> Read<'_> { Read { refused: why, method: "", target: "", length: 0, keep_alive: false, headers: vec![] } }

