// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

use winnow_grammar::grammar;
#[allow(unused_imports)]
pub use nikaia_std::error::Full;

#[allow(unused_imports)]
use nikaia_std::collections;

#[allow(unused_imports)]
use nikaia_std::text;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Line<'a> {
    Table { kind: &'a str, name: &'a str },
    Sources,
    Pair { key: &'a str, value: &'a str },
    Nothing,
    Unterminated,
    Bad(&'a str),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Refused {
    Because(String),
}

impl Refused {
    fn message(&self) -> String {
        match self {
            Refused::Because(why) => why.to_owned(),
        }
    }
}
impl std::fmt::Display for Refused {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message())
    }
}
impl std::error::Error for Refused {}

grammar! {
    grammar LedgerText {

        rule WS =
            ""
            -> { }

        pub rule file -> Vec<Line<'a>> =
            ls:line* last:BODY eof
            -> {
                let mut all = Vec::new();
                for l in ls.into_iter() { all.push(l); }
                all.push(last);
                all
            }

        rule line -> Line<'a> =
            l:BODY line_ending
            -> { l }

        rule BODY -> Line<'a> =
            SP l:AFTER
            -> { l }

        rule AFTER -> Line<'a> =
            "#" REST
            -> { Line::Nothing }
          | "[" t:TABLE
            -> { t }
          | peek(END)
            -> { Line::Nothing }
          | k:text(KEY) "=" v:text(REST)
            -> { Line::Pair { key: k.trim(), value: v.trim() } }
          | r:text(REST)
            -> { Line::Bad(r.trim()) }

        rule TABLE -> Line<'a> =
            "sources]" SP peek(END)
            -> { Line::Sources }
          | k:KIND ".\"" n:text(NAME) CLOSE
            -> { Line::Table { kind: k, name: n } }
          | KIND ".\"" REST
            -> { Line::Unterminated }

        rule KIND -> &'a str =
            "fn"
            -> { "fn" }
          | "type"
            -> { "type" }
          | "trait"
            -> { "trait" }
          | "impl"
            -> { "impl" }

        rule SP =
            SPACE*
            -> { }

        rule SPACE =
            " "
            -> { }
          | "\t"
            -> { }

        rule END =
            line_ending
            -> { }
          | eof
            -> { }

        rule REST =
            until(line_ending | eof)
            -> { }

        rule CLOSE =
            "\"]" SP peek(END)
            -> { }

        rule NAME =
            until("\"]" | line_ending | eof)
            -> { }

        rule KEY =
            until("=" | line_ending | eof)
            -> { }
    }
}

grammar! {
    grammar LedgerValue {

        pub rule list -> Vec<&'a str> =
            "[" items:__nikaia_list<&'a str>(item = QUOTED, sep = ",") TRAILING "]" eof
            -> { items }

        rule TRAILING =
            ","
            -> { }
          | empty
            -> { }

        rule QUOTED -> &'a str =
            "\"" s:text(INSIDE) "\""
            -> { s }

        rule INSIDE =
            PIECE*
            -> { }

        rule PIECE =
            ESCAPED
            -> { }
          | not("\"") not("\\") any
            -> { }

        rule ESCAPED =
            "\\" any
            -> { }

        rule __nikaia_list<T>(item: Rule<T>, sep) -> Vec<T> =
          first:item rest:__nikaia_list_more<T>(item = item, sep = sep)*
            -> { let mut all = vec![first]; all.extend(rest); all }
        | ""
            -> { Vec::new() }

        rule __nikaia_list_more<T>(item: Rule<T>, sep) -> T =
          sep x:item
            -> { x }
    }
}

pub fn unquote(value: &str) -> Result<String, nikaia_std::error::Thrown<Refused>> {
    Ok(unquote_at(value, "")?)
}

fn unquote_at(value: &str, at: &str) -> Result<String, nikaia_std::error::Thrown<Refused>> {
    if (value.len() as i64) < 2 || !value.starts_with("\"") || !value.ends_with("\"") { return Err(nikaia_std::error::throwing(Refused::Because(format!("{}expected a quoted string, found `{}`", at, value)), &"unquote_at")); }
    Ok(unescaped(nikaia_std::index::get(&value, nikaia_std::index::at(1..value.len() as i64 - 1))))
}

pub fn list(value: &str) -> Result<Vec<String>, nikaia_std::error::Thrown<Refused>> {
    Ok(list_at(value, "")?)
}

fn list_at(value: &str, at: &str) -> Result<Vec<String>, nikaia_std::error::Thrown<Refused>> {
    if value == "[]" { return Ok(vec![]); }
    let entries = match {
        use winnow::Parser;
        let _source = &*value;
        let mut stream = winnow_grammar::ParseInput::<()> {
            state: winnow_grammar::ParseContext::<()>::default(),
            input: winnow::stream::LocatingSlice::new(_source),
        };
        LedgerValue::parse_list()
            .parse_next(&mut stream)
            .map_err(|error| ParseError::of(error.render(_source)))
    } {
        Ok(value) => value,
        Err(_error) => { return Err(nikaia_std::error::throwing(Refused::Because(format!("{}expected a list, found `{}`", at, value)), &"list_at")) },
    };
    let mut out: Vec<String> = vec![];
    for entry in entries.iter() {
        let entry = *entry;
        out.push(unescaped(entry));
    }
    Ok(out)
}

fn unescaped(inside: &str) -> String {
    if !inside.contains("\\") { return inside.to_owned(); }
    let mut out: String = String::from("");
    let mut escaped = false;
    for c in inside.chars() {
        if escaped {
            if c == 'n' { out.push('\n'); } else { out.push(c); }
            escaped = false;
        } else if c == '\\' { escaped = true; } else { out.push(c); }
    }
    out
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Section {
    Header,
    Function,
    Kind,
    Sources,
    Nothing,
}

pub fn read(written: &str) -> Result<Ledger, nikaia_std::error::Thrown<Refused>> {
    let mut ledger = Ledger::blank();
    let mut section = Section::Header;
    let mut current: String = String::from("");
    let mut function = FnContract::empty();
    let mut a_type = TypeContract::empty();
    let mut traits: Vec<String> = vec![];
    let mut functions: Vec<String> = vec![];
    let mut answers: Vec<(String, String)> = vec![];
    let lines = match {
        use winnow::Parser;
        let _source = &*written;
        let mut stream = winnow_grammar::ParseInput::<()> {
            state: winnow_grammar::ParseContext::<()>::default(),
            input: winnow::stream::LocatingSlice::new(_source),
        };
        LedgerText::parse_file()
            .parse_next(&mut stream)
            .map_err(|error| ParseError::of(error.render(_source)))
    } {
        Ok(value) => value,
        Err(error) => { return Err(nikaia_std::error::throwing(Refused::Because(format!("{}", error)), &"read")) },
    };
    let mut n: i64 = 0;
    for one in lines.iter() {
        n += 1;
        match one {
            Line::Table { kind, name } => {
                let kind = *kind; let name = *name;
                if section == Section::Function {
                    ledger.functions.insert(current.to_owned(), function);
                    function = FnContract::empty();
                }
                if section == Section::Kind {
                    ledger.types.insert(current.to_owned(), a_type);
                    a_type = TypeContract::empty();
                }
                current = name.to_owned();
                if kind == "fn" {
                    if ledger.functions.contains_key(&current) {
                        function = nikaia_std::index::or(match *nikaia_std::index::get(&ledger.functions, &current) {
                            Some(__nikaia_it) => Some(__nikaia_it.clone()),
                            None => None,
                        }, || FnContract::empty());
                    }
                    functions.push(current.to_owned());
                    section = Section::Function;
                } else if kind == "type" {
                    if ledger.types.contains_key(&current) {
                        a_type = nikaia_std::index::or(match *nikaia_std::index::get(&ledger.types, &current) {
                            Some(__nikaia_it) => Some(__nikaia_it.clone()),
                            None => None,
                        }, || TypeContract::empty());
                    }
                    section = Section::Kind;
                } else if kind == "trait" {
                    if !ledger.traits.contains_key(&current) { ledger.traits.insert(current.to_owned(), collections::BTreeSet::new()); }
                    traits.push(current.to_owned());
                    section = Section::Nothing;
                } else {
                    answers.push(implemented(&current, n)?);
                    section = Section::Nothing;
                }
            },
            Line::Sources => {
                if section == Section::Function {
                    ledger.functions.insert(current.to_owned(), function);
                    function = FnContract::empty();
                }
                if section == Section::Kind {
                    ledger.types.insert(current.to_owned(), a_type);
                    a_type = TypeContract::empty();
                }
                section = Section::Sources;
            },
            Line::Pair { key, value } => {
                let key = *key; let value = *value;
                if section == Section::Header { header(&mut ledger, key, value, n)?; } else if section == Section::Sources { ledger.sources.insert(unquoted(key, n)?, unquoted(value, n)?); } else if section == Section::Function { function_key(&mut function, &current, key, value, n)?; } else if section == Section::Kind { type_key(&mut a_type, key, value, n)?; } else { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: a `trait` or an `impl` table has no keys, and this has `{}`", n, key)), &"read")); }
            },
            Line::Unterminated => { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: unterminated section header", n)), &"read")); },
            Line::Bad(text) => {
                let text = *text;
                return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: not a key and a value: {}", n, text)), &"read"));
            },
            Line::Nothing => { },
        }
    }
    if section == Section::Function { ledger.functions.insert(current.to_owned(), function); }
    if section == Section::Kind { ledger.types.insert(current.to_owned(), a_type); }
    for name in traits.iter() {
        let prefix = format!("{}::", name);
        let mut methods: collections::BTreeSet<String> = collections::BTreeSet::new();
        for entry in functions.iter() {
            let method = after(entry, &prefix);
            if method.is_some() {
                let rest = nikaia_std::index::or(method, || "".into());
                if !rest.contains("::") { methods.insert(rest.to_owned()); }
            }
        }
        ledger.traits.insert(name.to_owned(), methods);
    }
    let mut done: Vec<String> = vec![];
    for (trait_name, _) in answers.iter() {
        if !done.contains(trait_name) {
            let mut types: collections::BTreeSet<String> = collections::BTreeSet::new();
            for (other, answering) in answers.iter() { if other == trait_name { types.insert(answering.to_owned()); } }
            ledger.implementations.insert(trait_name.to_owned(), types);
            done.push(trait_name.to_owned());
        }
    }
    Ok(ledger)
}

fn header(ledger: &mut Ledger, key: &str, value: &str, n: i64) -> Result<(), nikaia_std::error::Thrown<Refused>> {
    if key == "version" {
        let number = nikaia_std::index::or(text::parse_i64(value), || -1);
        if number < 0 { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: `version` is a whole number, not `{}`", n, value)), &"header")); }
        if number > 4294967295i64 { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: `version` is a whole number, not `{}`", n, value)), &"header")); }
        ledger.version = u32::try_from(number).unwrap_or_else(|_| panic!("the value does not fit in an `u32`"));
    } else if key == "toolchain" { ledger.toolchain = unquoted(value, n)?; } else if key == "inference" { ledger.inference = unquoted(value, n)?; } else { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: unknown header key `{}`", n, key)), &"header")); }
    Ok(())
}

fn implemented(name: &str, n: i64) -> Result<(String, String), nikaia_std::error::Thrown<Refused>> {
    let c: Vec<char> = nikaia_std::list::chars(name.chars());
    let at = find_text(&c, 0, " for ");
    if at < 0 { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: an `impl` entry is `A for T`: {}", n, name)), &"implemented")); }
    Ok((trimmed(&slice(&c, 0, at)), trimmed(&slice(&c, at + 5, c.len() as i64))))
}

fn function_key(entry: &mut FnContract, name: &str, key: &str, value: &str, n: i64) -> Result<(), nikaia_std::error::Thrown<Refused>> {
    if key == "pub" { entry.public = value == "true"; } else if key == "sync" { entry.sync_claim = sync_of(value, n)?; } else if key == "throws" { entry.fails_with = throws_of(value, n)?; } else if key == "returns" { entry.borrows = borrows_of(&unquoted(value, n)?, n)?; } else if key == "signature" {
        let spelled = spelled_signature(&unquoted(value, n)?, name)?;
        if spelled.mutates { entry.mutates = true; }
        if (spelled.borrows.len() as i64) > 0 { entry.borrows = spelled.borrows.to_owned(); }
        entry.signature = Some(spelled.signature);
    } else if key == "keeps" { entry.keeps = entries(value, n)?; } else if key == "mutates" { entry.mutates = value == "true"; } else if key == "locks" {
        let said = value.trim();
        if said == "true" { entry.touches_a_lock = Lock::Holds; } else if said == "\"?\"" { entry.touches_a_lock = Lock::Undecided; } else { entry.touches_a_lock = Lock::No; }
    } else if key == "threads" {
        let said = value.trim();
        if said == "true" { entry.threads = Threads::May; } else if said == "false" { entry.threads = Threads::MayNot; } else { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: `threads` is `true` or `false`, not `{}`. (Leave it out if nobody knows.)", n, said)), &"function_key")); }
    } else if key == "touches" {
        let mut touches: Vec<Touch> = vec![];
        for one in entries(value, n)? { touches.push(touch_of(&one)?); }
        entry.touches = touches;
        entry.touches_known = true;
    } else if key == "provenance" { entry.provenance = Some(provenance_of(&unquoted(value, n)?, n)?); } else if key == "views" {
        let mut views: Vec<Held> = vec![];
        for held in entries(value, n)? {
            let read = held_of(&held);
            if read.is_none() { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: a tether state is `name: borrowed` or `name: tethered`, not `{}`", n, held)), &"function_key")); }
            views.push(nikaia_std::index::or(read, || Held { position: String::from(""), state: State::Borrowed }));
        }
        entry.views = views;
    } else if key == "sharing" {
        let mut classes: Vec<Class> = vec![];
        for class in entries(value, n)? {
            let read = class_of(&class);
            if read.is_none() { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: a sharing class is `a | b: plain` or `a | b: atomic`, not `{}`", n, class)), &"function_key")); }
            classes.push(nikaia_std::index::or(read, || Class { members: vec![], count: Count::Atomic }));
        }
        entry.sharing = classes;
    } else if key == "ends_by_length" { entry.ends_by_length = value == "true"; } else { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: unknown key `{}` on a fn", n, key)), &"function_key")); }
    Ok(())
}

fn type_key(entry: &mut TypeContract, key: &str, value: &str, n: i64) -> Result<(), nikaia_std::error::Thrown<Refused>> {
    if key == "pub" { entry.public = value == "true"; } else if key == "crosses" { if value == "true" { entry.crosses = Crosses::May; } else if value == "false" { entry.crosses = Crosses::MayNot; } else { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: `crosses` is `true` or `false`, not `{}` - and leaving the line out is the third answer", n, value)), &"type_key")); } } else if key == "compares" { entry.compares = value.trim() == "true"; } else if key == "copies" { entry.copies = value.trim() == "true"; } else if key == "tethered" { entry.tethered = entries(value, n)?; } else if key == "touches" { entry.touches = entries(value, n)?; } else if key == "iterates" {
        let said = unquoted(value, n)?;
        if said != "throws" { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: `iterates` is `throws` and nothing else, not `{}` - a step that cannot fail says nothing", n, said)), &"type_key")); }
        entry.iterates_fallibly = true;
    } else if key == "variants" {
        let mut variants: Vec<VariantContract> = vec![];
        for one in entries(value, n)? { variants.push(variant_of(&one)); }
        entry.variants = variants;
    } else if key == "fields" {
        let mut fields: Vec<FieldContract> = vec![];
        for one in entries(value, n)? { fields.push(field_of(&one)); }
        entry.fields = fields;
    } else { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: unknown key `{}` on a type", n, key)), &"type_key")); }
    Ok(())
}

fn unquoted(value: &str, n: i64) -> Result<String, nikaia_std::error::Thrown<Refused>> {
    Ok(unquote_at(value, &format!("line {}: ", n))?)
}

fn entries(value: &str, n: i64) -> Result<Vec<String>, nikaia_std::error::Thrown<Refused>> {
    Ok(list_at(value, &format!("line {}: ", n))?)
}

fn sync_of(value: &str, n: i64) -> Result<Sync, nikaia_std::error::Thrown<Refused>> {
    if value == "true" { return Ok(Sync::Asserted); }
    if value == "false" { return Ok(Sync::No); }
    if value == "\"inferred\"" { return Ok(Sync::Inferred); }
    let c: Vec<char> = nikaia_std::list::chars(value.chars());
    if value.ends_with(")\"") && (value.starts_with("\"sync(") || value.starts_with("\"from(")) && (c.len() as i64) >= 8 {
        let inside = slice(&c, 6, c.len() as i64 - 2);
        let name = inside.trim();
        if (name.len() as i64) > 0 { return Ok(Sync::From(name.to_owned())); }
    }
    return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: `sync` is `true` (the source says so), `\"inferred\"` (the body implies it) or `\"sync(f)\"` (its lambda decides), not `{}`", n, value)), &"sync_of"))
}

fn throws_of(value: &str, n: i64) -> Result<Vec<String>, nikaia_std::error::Thrown<Refused>> {
    if value == "true" {
        let unnamed: String = String::from("?");
        return Ok(vec![unnamed]);
    }
    Ok(entries(value, n)?)
}

fn borrows_of(value: &str, n: i64) -> Result<Vec<String>, nikaia_std::error::Thrown<Refused>> {
    let c: Vec<char> = nikaia_std::list::chars(value.chars());
    let mut from: i64 = -1;
    if value.ends_with(")") { if value.starts_with("ref(") { from = 4; } else if value.starts_with("borrows(") { from = 8; } }
    if from < 0 { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: expected `ref(…)`, found `{}`", n, value)), &"borrows_of")); }
    let inside = slice(&c, from, c.len() as i64 - 1);
    let mut names: Vec<String> = vec![];
    for part in inside.split("|") {
        let name = part.trim();
        if (name.len() as i64) > 0 { names.push(name.to_owned()); }
    }
    Ok(names)
}

fn provenance_of(value: &str, n: i64) -> Result<Provenance, nikaia_std::error::Thrown<Refused>> {
    if value == "trusted" { return Ok(Provenance::Trusted); }
    if value == "untrusted" { return Ok(Provenance::Untrusted); }
    return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: a provenance is `trusted` or `untrusted`, not `{}`", n, value)), &"provenance_of"))
}

pub fn touch_of(written: &str) -> Result<Touch, nikaia_std::error::Thrown<Refused>> {
    let __keep_frame = nikaia_std::tether::Keep::new();
    let whole = written.trim();
    let c: Vec<char> = nikaia_std::list::chars(whole.chars());
    let space = find_last(&c, ' ');
    if space < 0 { return Err(nikaia_std::error::throwing(Refused::Because(format!("a touch is `resource read` or `resource write`, found `{}`", whole)), &"touch_of")); }
    let said = slice(&c, space + 1, c.len() as i64);
    let access = said.trim();
    let mut write = false;
    if access == "write" { write = true; } else if access != "read" { return Err(nikaia_std::error::throwing(Refused::Because(format!("a touch is `read` or `write`, not `{}` (in `{}`)", access, whole)), &"touch_of")); }
    let before = slice(&c, 0, space);
    let resource = before.trim();
    let r: Vec<char> = nikaia_std::list::chars(resource.chars());
    let open = find(&r, 0, '(');
    let mut kind: String = resource.to_owned();
    let mut parameter: Option<String> = None;
    if open >= 0 {
        if !resource.ends_with(")") { return Err(nikaia_std::error::throwing(Refused::Because(format!("a resource is `kind(parameter)`, and `{}` has no `)`", resource)), &"touch_of")); }
        let named = __keep_frame.put(slice(&r, 0, open));
        kind = named.trim().to_owned();
        let inside = __keep_frame.put(slice(&r, open + 1, r.len() as i64 - 1));
        parameter = Some(inside.trim().to_owned());
    }
    if (kind.len() as i64) == 0 { return Err(nikaia_std::error::throwing(Refused::Because(format!("a touch needs a resource kind, found `{}`", whole)), &"touch_of")); }
    Ok(Touch { kind, parameter, write })
}

pub fn held_of(written: &str) -> Option<Held> {
    let c: Vec<char> = nikaia_std::list::chars(written.chars());
    let colon = find_last(&c, ':');
    if colon < 0 { return None; }
    let state = State::parse(&slice(&c, colon + 1, c.len() as i64));
    if state.is_none() { return None; }
    let position = slice(&c, 0, colon);
    Some(Held { position: position.trim().to_owned(), state: nikaia_std::index::or(state, || State::Borrowed) })
}

pub fn class_of(written: &str) -> Option<Class> {
    let c: Vec<char> = nikaia_std::list::chars(written.chars());
    let colon = find_last(&c, ':');
    if colon < 0 { return None; }
    let named = slice(&c, 0, colon);
    let mut members: Vec<String> = vec![];
    for part in named.split("|") {
        let member = part.trim();
        if (member.len() as i64) > 0 { members.push(member.to_owned()); }
    }
    if (members.len() as i64) == 0 { return None; }
    let count = Count::parse(&slice(&c, colon + 1, c.len() as i64));
    if count.is_none() { return None; }
    Some(Class { members, count: nikaia_std::index::or(count, || Count::Atomic) })
}

pub fn variant_of(written: &str) -> VariantContract {
    let __keep_frame = nikaia_std::tether::Keep::new();
    let whole = written.trim();
    let c: Vec<char> = nikaia_std::list::chars(whole.chars());
    let paren = find(&c, 0, '(');
    if paren >= 0 {
        let named = slice(&c, 0, paren);
        let rest = slice(&c, paren + 1, c.len() as i64);
        let inside = without_last(rest.trim_end(), ')');
        let mut holds: Vec<FieldContract> = vec![];
        let mut at = 0;
        for part in split_args(&inside) {
            holds.push(FieldContract { name: format!("{}", at), ty: parse(&part), public: true });
            at += 1;
        }
        return VariantContract { name: named.trim().to_owned(), holds, positional: true };
    }
    let brace = find(&c, 0, '{');
    if brace >= 0 {
        let named = slice(&c, 0, brace);
        let rest = slice(&c, brace + 1, c.len() as i64);
        let inside = without_last(rest.trim_end(), '}');
        let mut holds: Vec<FieldContract> = vec![];
        for part in split_args(&inside) {
            let p: Vec<char> = nikaia_std::list::chars(part.chars());
            let colon = find(&p, 0, ':');
            if colon >= 0 {
                let field = __keep_frame.put(slice(&p, 0, colon));
                holds.push(FieldContract { name: field.trim().to_owned(), ty: parse(&slice(&p, colon + 1, p.len() as i64)), public: true });
            }
        }
        return VariantContract { name: named.trim().to_owned(), holds, positional: false };
    }
    let nothing: Vec<FieldContract> = vec![];
    VariantContract { name: whole.to_owned(), holds: nothing, positional: false }
}

fn field_of(written: &str) -> FieldContract {
    let __keep_frame = nikaia_std::tether::Keep::new();
    let mut field: String = written.trim().to_owned();
    let mut public = false;
    if field.starts_with("pub ") {
        public = true;
        let rest = __keep_frame.put(from_char(&field, 4));
        field = rest.trim().to_owned();
    }
    let c: Vec<char> = nikaia_std::list::chars(field.chars());
    let colon = find(&c, 0, ':');
    if colon < 0 { return FieldContract { name: field.to_owned(), ty: Ty::Unknown, public }; }
    let name = slice(&c, 0, colon);
    FieldContract { name: name.trim().to_owned(), ty: parse(&slice(&c, colon + 1, c.len() as i64)), public }
}

pub fn signature_of(written: &str) -> Result<Signature, nikaia_std::error::Thrown<Refused>> {
    let spelled = spelled_signature(written, "")?;
    Ok(spelled.signature)
}

#[derive(Debug, Clone)]
pub struct Spelling {
    pub signature: Signature,
    pub borrows: Vec<String>,
    pub mutates: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum Part<'a> {
    Owner { view: bool, mutates: bool },
    Typed { ty: &'a str, mutates: bool },
    Named { name: &'a str, ty: &'a str, mutable: bool },
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Declared<'a> {
    name: &'a str,
    traits: Vec<&'a str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Setting<'a> {
    name: &'a str,
    ty: &'a str,
    default: &'a str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Written<'a> {
    declared: Vec<Declared<'a>>,
    parts: Vec<Part<'a>>,
    settings: Vec<Setting<'a>>,
    result: Option<&'a str>,
}

grammar! {
    grammar SignatureText {

        pub rule signature -> Written<'a> =
            d:bracket "(" ps:__nikaia_list<Part<'a>>(item = part, sep = ",") TRAILING ss:settings ")" r:result? eof
            -> { Written { declared: d, parts: ps, settings: ss, result: r.into() } }

        rule bracket -> Vec<Declared<'a>> =
            "[" ds:__nikaia_list<Declared<'a>>(item = declared, sep = ",") "]"
            -> { ds }
          | empty
            -> { Vec::new() }

        rule declared -> Declared<'a> =
            n:raw_ident COLON ts:__nikaia_list<&'a str>(item = BOUND, sep = "+")
            -> { Declared { name: n, traits: ts } }
          | n:raw_ident
            -> { Declared { name: n, traits: Vec::new() } }

        rule part -> Part<'a> =
            REF MUT SELF
            -> { Part::Owner { view: true, mutates: true } }
          | REF SELF
            -> { Part::Owner { view: true, mutates: false } }
          | MUT SELF COLON t:TYPE
            -> { Part::Typed { ty: t, mutates: true } }
          | SELF COLON t:TYPE
            -> { Part::Typed { ty: t, mutates: false } }
          | SELF
            -> { Part::Owner { view: false, mutates: false } }
          | MUT n:raw_ident COLON t:TYPE
            -> { Part::Named { name: n, ty: t, mutable: true } }
          | n:raw_ident COLON t:TYPE
            -> { Part::Named { name: n, ty: t, mutable: false } }
          | t:TYPE
            -> { Part::Typed { ty: t, mutates: false } }

        rule settings -> Vec<Setting<'a>> =
            ";" ss:__nikaia_list<Setting<'a>>(item = setting, sep = ",") TRAILING
            -> { ss }
          | empty
            -> { Vec::new() }

        rule setting -> Setting<'a> =
            n:raw_ident COLON t:SETTING_TYPE "=" d:DEFAULT
            -> { Setting { name: n, ty: t, default: d } }

        rule result -> &'a str =
            "->" t:REST
            -> { t }

        pub rule pointed -> Vec<Vec<&'a str>> =
            ps:POINTING* eof
            -> { ps }

        rule POINTING -> Vec<&'a str> =
            "ref(" ns:__nikaia_list<&'a str>(item = POINTED_NAME, sep = "|") ")"
            -> { ns }
          | WORD_CHARS
            -> { Vec::new() }
          | any
            -> { Vec::new() }

        rule POINTED_NAME -> &'a str =
            WS0 n:raw_ident WS0
            -> { n }

        rule WS0 =
            " "*
            -> { }

        rule WORD_CHARS =
            WORD_CHAR+
            -> { }

        rule WORD_CHAR =
            alpha1
            -> { }
          | digit
            -> { }
          | "_"
            -> { }
          | "$"
            -> { }

        rule REF =
            "ref" not(WORD_CHAR)
            -> { }

        rule MUT =
            "mut" not(WORD_CHAR)
            -> { }

        rule SELF =
            "self" not(WORD_CHAR)
            -> { }

        rule COLON =
            ":" not(":")
            -> { }

        rule TRAILING =
            ","
            -> { }
          | empty
            -> { }

        rule BOUND -> &'a str =
            t:text(BOUND_RUN)
            -> { t.trim() }

        rule BOUND_RUN =
            BOUND_PIECE+
            -> { }

        rule BOUND_PIECE =
            not("+") not(",") not("]") SPAN
            -> { }

        rule TYPE -> &'a str =
            t:text(TYPE_RUN)
            -> { t.trim() }

        rule TYPE_RUN =
            TYPE_PIECE+
            -> { }

        rule TYPE_PIECE =
            not(",") not(")") not(";") SPAN
            -> { }

        rule SETTING_TYPE -> &'a str =
            t:text(SETTING_RUN)
            -> { t.trim() }

        rule SETTING_RUN =
            SETTING_PIECE+
            -> { }

        rule SETTING_PIECE =
            not("=") not(",") not(")") SPAN
            -> { }

        rule DEFAULT -> &'a str =
            t:text(DEFAULT_RUN)
            -> { t.trim() }

        rule DEFAULT_RUN =
            DEFAULT_PIECE+
            -> { }

        rule DEFAULT_PIECE =
            not(",") not(")") SPAN
            -> { }

        rule REST -> &'a str =
            t:text(REST_RUN)
            -> { t.trim() }

        rule REST_RUN =
            until(eof)
            -> { }

        rule SPAN =
            PARENS
            -> { }
          | BRACKETS
            -> { }
          | STRING
            -> { }
          | any
            -> { }

        rule PARENS =
            "(" IN_PARENS* ")"
            -> { }

        rule IN_PARENS =
            not(")") SPAN
            -> { }

        rule BRACKETS =
            "[" IN_BRACKETS* "]"
            -> { }

        rule IN_BRACKETS =
            not("]") SPAN
            -> { }

        rule STRING =
            "\"" STRING_PIECE* "\""
            -> { }

        rule STRING_PIECE =
            "\\" any
            -> { }
          | not("\"") any
            -> { }

        rule __nikaia_list<T>(item: Rule<T>, sep) -> Vec<T> =
          first:item rest:__nikaia_list_more<T>(item = item, sep = sep)*
            -> { let mut all = vec![first]; all.extend(rest); all }
        | ""
            -> { Vec::new() }

        rule __nikaia_list_more<T>(item: Rule<T>, sep) -> T =
          sep x:item
            -> { x }
    }
}

pub fn spelled_signature(written: &str, key: &str) -> Result<Spelling, nikaia_std::error::Thrown<Refused>> {
    let parts = match {
        use winnow::Parser;
        let _source = &*written;
        let mut stream = winnow_grammar::ParseInput::<()> {
            state: winnow_grammar::ParseContext::<()>::default(),
            input: winnow::stream::LocatingSlice::new(_source),
        };
        SignatureText::parse_signature()
            .parse_next(&mut stream)
            .map_err(|error| ParseError::of(error.render(_source)))
    } {
        Ok(value) => value,
        Err(_error) => { return Err(nikaia_std::error::throwing(Refused::Because(format!("a signature is `[T](a: A; o: O = v) -> R`, found `{}`", written)), &"spelled_signature")) },
    };
    let mut variables: collections::BTreeSet<String> = collections::BTreeSet::new();
    let mut bounds: Vec<(String, Vec<String>)> = vec![];
    for declared in parts.declared.iter() {
        variables.insert(declared.name.to_owned());
        if (declared.traits.len() as i64) > 0 {
            let mut traits: Vec<String> = vec![];
            for one in declared.traits.iter() {
                let one = *one;
                traits.push(one.to_owned());
            }
            bounds.push(a_bound(declared.name, traits));
        }
    }
    let mut params: Vec<(String, Ty)> = vec![];
    let mut changed: Vec<String> = vec![];
    let mut order: Vec<String> = vec![];
    let mut receiver_changes = false;
    let mut first = true;
    for part in parts.parts.iter() {
        match part {
            Part::Owner { view, mutates } => {
                let mutates = *mutates; let view = *view;
                let owner = nikaia_std::index::or(owner_of(key), || "?".into());
                let written_type = if view { format!("ref {}", owner) } else { owner.to_owned() };
                params.push(a_param("self", typed(&written_type, &variables)));
                if mutates { receiver_changes = true; }
                if first { order.push(a_receiver()); }
            },
            Part::Typed { ty, mutates } => {
                let mutates = *mutates; let ty = *ty;
                params.push(a_param("self", typed(ty, &variables)));
                if mutates { receiver_changes = true; }
                if first { order.push(a_receiver()); }
            },
            Part::Named { name, ty, mutable } => {
                let mutable = *mutable; let name = *name; let ty = *ty;
                params.push(a_param(name, typed(ty, &variables)));
                if mutable { changed.push(name.to_owned()); }
                order.push(name.to_owned());
            },
        }
        first = false;
    }
    let mut config: Vec<ConfigContract> = vec![];
    for setting in parts.settings.iter() { config.push(ConfigContract { name: setting.name.to_owned(), ty: typed(setting.ty, &variables), default: setting.default.to_owned() }); }
    let mut result: Option<Ty> = None;
    let mut borrows: Vec<String> = vec![];
    let result_text = nikaia_std::index::or(parts.result, || "");
    if parts.result.is_some() {
        result = Some(typed(result_text, &variables));
        borrows = pointed_into(result_text, &order);
    }
    Ok(Spelling { signature: Signature { bounds, params, mutable: changed, config, result }, borrows, mutates: receiver_changes })
}

fn typed(written: &str, variables: &collections::BTreeSet<String>) -> Ty {
    let ty = parse(written);
    if (variables.len() as i64) == 0 { return ty; }
    ty.parameterise(variables)
}

fn pointed_into(result: &str, order: &Vec<String>) -> Vec<String> {
    if !result.contains("ref(") { return vec![]; }
    let groups = match {
        use winnow::Parser;
        let _source = &*result;
        let mut stream = winnow_grammar::ParseInput::<()> {
            state: winnow_grammar::ParseContext::<()>::default(),
            input: winnow::stream::LocatingSlice::new(_source),
        };
        SignatureText::parse_pointed()
            .parse_next(&mut stream)
            .map_err(|error| ParseError::of(error.render(_source)))
    } {
        Ok(value) => value,
        Err(_error) => { return vec![]; },
    };
    let mut named: Vec<String> = vec![];
    for group in groups.iter() {
        for name in group.iter() {
            let name = *name;
            if !named.contains(&name.to_owned()) { named.push(name.to_owned()); }
        }
    }
    let mut borrows: Vec<String> = vec![];
    for name in order.iter() { if named.contains(name) { borrows.push(name.to_owned()); } }
    for name in named.iter() { if !borrows.contains(name) { borrows.push(name.to_owned()); } }
    borrows
}

fn a_bound(name: &str, traits: Vec<String>) -> (String, Vec<String>) { (name.to_owned(), traits) }

fn a_receiver() -> String {
    let receiver: String = String::from("self");
    receiver
}

fn owner_of(key: &str) -> Option<String> {
    let c: Vec<char> = nikaia_std::list::chars(key.chars());
    let mut last: i64 = -1;
    for at in 0..c.len() as i64 { if at + 1 < c.len() as i64 && *nikaia_std::index::get(&c, nikaia_std::index::at(at)) == ':' && *nikaia_std::index::get(&c, nikaia_std::index::at(at + 1)) == ':' { last = at; } }
    if last < 0 { return None; }
    Some(slice(&c, 0, last))
}

fn find(c: &[char], from: i64, target: char) -> i64 {
    for at in from..c.len() as i64 { if *nikaia_std::index::get(&c, nikaia_std::index::at(at)) == target { return at; } }
    -1
}

fn find_last(c: &[char], target: char) -> i64 {
    let mut found: i64 = -1;
    for at in 0..c.len() as i64 { if *nikaia_std::index::get(&c, nikaia_std::index::at(at)) == target { found = at; } }
    found
}

fn find_text(c: &[char], from: i64, word: &str) -> i64 {
    let w: Vec<char> = nikaia_std::list::chars(word.chars());
    if (w.len() as i64) == 0 || (c.len() as i64) < w.len() as i64 { return -1; }
    for at in from..c.len() as i64 - w.len() as i64 + 1 {
        let mut same = true;
        for k in 0..w.len() as i64 { if same && *nikaia_std::index::get(&c, nikaia_std::index::at(at + k)) != *nikaia_std::index::get(&w, nikaia_std::index::at(k)) { same = false; } }
        if same { return at; }
    }
    -1
}

fn slice(c: &[char], from: i64, to: i64) -> String {
    let mut out: String = String::from("");
    for k in from..to { out.push(*nikaia_std::index::get(&c, nikaia_std::index::at(k))); }
    out
}

fn from_char(written: &str, front: i64) -> String {
    let c: Vec<char> = nikaia_std::list::chars(written.chars());
    slice(&c, front, c.len() as i64)
}

fn after(written: &str, prefix: &str) -> Option<String> {
    if !written.starts_with(prefix) { return None; }
    let p: Vec<char> = nikaia_std::list::chars(prefix.chars());
    Some(from_char(written, p.len() as i64))
}

fn without_last(written: &str, last: char) -> String {
    let c: Vec<char> = nikaia_std::list::chars(written.chars());
    let mut end = c.len() as i64;
    while end > 0 && *nikaia_std::index::get(&c, nikaia_std::index::at(end - 1)) == last { end -= 1; }
    slice(&c, 0, end)
}

fn a_param(name: &str, ty: Ty) -> (String, Ty) { (name.to_owned(), ty) }

fn trimmed(written: &str) -> String { written.trim().to_owned() }

