// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

#[allow(unused_imports)]
pub use nikaia_std::error::Full;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Line {
    Table { kind: String, name: String },
    Sources,
    Pair { key: String, value: String },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Read {
    pub at: i64,
    pub line: Line,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Refused {
    Because(String),
}

impl Refused {
    fn message(&self) -> String {
        match self {
            Refused::Because(why) => why.to_owned(),
        }
    }
}
impl std::fmt::Display for Refused {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message())
    }
}
impl std::error::Error for Refused {}

pub fn lines(text: &str) -> Result<Vec<Read>, nikaia_std::error::Thrown<Refused>> {
    let mut read: Vec<Read> = vec![];
    let mut n: i64 = 0;
    for raw in text.lines() {
        n += 1;
        let line = raw.trim();
        if (line.len() as i64) == 0 || line.starts_with("#") { continue; }
        if line == "[sources]" {
            read.push(Read { at: n, line: Line::Sources });
            continue;
        }
        let kind = table_kind(line);
        if (kind.len() as i64) > 0 {
            read.push(Read { at: n, line: Line::Table { kind: kind.to_owned(), name: table_name(line, kind, n)? } });
            continue;
        }
        read.push(Read { at: n, line: pair(line, n)? });
    }
    Ok(read)
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
fn table_kind(line: &str) -> &str {
    if line.starts_with("[fn.\"") { return "fn"; }
    if line.starts_with("[type.\"") { return "type"; }
    if line.starts_with("[trait.\"") { return "trait"; }
    if line.starts_with("[impl.\"") { return "impl"; }
    ""
}

fn table_name(line: &str, kind: &str, n: i64) -> Result<String, nikaia_std::error::Thrown<Refused>> {
    let c: Vec<char> = line.chars().collect::<Vec<_>>();
    let start = kind.len() as i64 + 3;
    if !line.ends_with("\"]") || (c.len() as i64) < start + 2 { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: unterminated section header", n)), &"table_name")); }
    let mut name: String = String::from("");
    for k in start..c.len() as i64 - 2 { name.push(*nikaia_std::index::get(&c, nikaia_std::index::at(k))); }
    Ok(name)
}

fn pair(line: &str, n: i64) -> Result<Line, nikaia_std::error::Thrown<Refused>> {
    let mut key: String = String::from("");
    let mut value: String = String::from("");
    let mut seen = false;
    for c in line.chars() { if seen { value.push(c); } else if c == '=' { seen = true; } else { key.push(c); } }
    if !seen { return Err(nikaia_std::error::throwing(Refused::Because(format!("line {}: not a key and a value: {}", n, line)), &"pair")); }
    Ok(Line::Pair { key: key.trim().to_owned(), value: value.trim().to_owned() })
}

pub fn unquote(value: &str) -> Result<String, nikaia_std::error::Thrown<Refused>> {
    let c: Vec<char> = value.chars().collect::<Vec<_>>();
    if (c.len() as i64) < 2 || *nikaia_std::index::get(&c, 0) != '"' || *nikaia_std::index::get(&c, nikaia_std::index::at(c.len() as i64 - 1)) != '"' { return Err(nikaia_std::error::throwing(Refused::Because(format!("expected a quoted string, found `{}`", value)), &"unquote")); }
    let mut out: String = String::from("");
    let mut escaped = false;
    for k in 1..c.len() as i64 - 1 {
        if escaped {
            if *nikaia_std::index::get(&c, nikaia_std::index::at(k)) == 'n' { out.push('\n'); } else { out.push(*nikaia_std::index::get(&c, nikaia_std::index::at(k))); }
            escaped = false;
        } else if *nikaia_std::index::get(&c, nikaia_std::index::at(k)) == '\\' { escaped = true; } else { out.push(*nikaia_std::index::get(&c, nikaia_std::index::at(k))); }
    }
    if escaped { return Err(nikaia_std::error::throwing(Refused::Because(format!("a `\\` at the end of `{}`", value)), &"unquote")); }
    Ok(out)
}

pub fn list(value: &str) -> Result<Vec<String>, nikaia_std::error::Thrown<Refused>> {
    let c: Vec<char> = value.chars().collect::<Vec<_>>();
    if (c.len() as i64) < 2 || *nikaia_std::index::get(&c, 0) != '[' || *nikaia_std::index::get(&c, nikaia_std::index::at(c.len() as i64 - 1)) != ']' { return Err(nikaia_std::error::throwing(Refused::Because(format!("expected a list, found `{}`", value)), &"list")); }
    let mut entries: Vec<String> = vec![];
    let mut entry: String = String::from("");
    let mut quoted = false;
    let mut escaped = false;
    for k in 1..c.len() as i64 - 1 {
        let here = *nikaia_std::index::get(&c, nikaia_std::index::at(k));
        if quoted {
            if escaped { escaped = false; } else if here == '\\' { escaped = true; } else if here == '"' { quoted = false; }
            entry.push(here);
        } else if here == ',' {
            take(&entry, &mut entries)?;
            entry = String::from("");
        } else {
            if here == '"' { quoted = true; }
            entry.push(here);
        }
    }
    take(&entry, &mut entries)?;
    Ok(entries)
}

fn take(entry: &str, entries: &mut Vec<String>) -> Result<(), nikaia_std::error::Thrown<Refused>> {
    let written = entry.trim();
    if (written.len() as i64) > 0 { entries.push(unquote(written)?); }
    Ok(())
}

