// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

#[allow(unused_imports)]
pub use nikaia_std::error::Full;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Refused {
    Because(String),
}

impl Refused {
    fn message(&self) -> String {
        match self {
            Refused::Because(why) => why.to_owned(),
        }
    }
}
impl std::fmt::Display for Refused {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message())
    }
}
impl std::error::Error for Refused {}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Switch {
    Kept,
    Moved(String),
}

pub fn known() -> Vec<String> { vec![String::from("target"), String::from("user-parallelism"), String::from("reentrancy-check"), String::from("cleanup-deadline")] }

fn withdrawn(key: &str) -> String {
    if key == "ordering" { return String::from("statements run in the order they are written, so there's nothing left for it to turn off. To run two things together, write `overlap { … }`; `--overlaps` shows which branches did"); }
    String::from("")
}

fn moved(key: &str) -> String {
    if key == "cleanup-deadline" { return String::from("the runtime configuration file `nikaia-runtime.toml`, which is read when the program starts. How long a program waits at exit is set by whoever runs it, and the compiler no longer reads this key"); }
    String::from("")
}

pub fn build_key(key: &str) -> Result<Switch, nikaia_std::error::Thrown<Refused>> {
    let gone = withdrawn(key);
    if (gone.len() as i64) > 0 { return Err(nikaia_std::error::throwing(Refused::Because(format!("`{}` in `[build]` is no longer supported: {}", key, gone)), &"build_key")); }
    if !contains(&known(), key) {
        let expected = joined(&known());
        return Err(nikaia_std::error::throwing(Refused::Because(format!("`[build]` has no key called `{}`. The keys are: {}.", key, expected)), &"build_key"));
    }
    let went = moved(key);
    if (went.len() as i64) > 0 { return Ok(Switch::Moved(format!("`{}` in `[build]` has moved to {}", key, went))); }
    Ok(Switch::Kept)
}

pub fn targets() -> Vec<String> { vec![String::from("x86_64-linux"), String::from("aarch64-linux"), String::from("wasm32-unknown")] }

pub fn codegen_keys() -> Vec<String> { vec![String::from("opt-level"), String::from("lto")] }

pub fn codegen_table(target: &str) -> Result<(), nikaia_std::error::Thrown<Refused>> {
    if !contains(&targets(), target) {
        let expected = joined(&targets());
        return Err(nikaia_std::error::throwing(Refused::Because(format!("`[build.{}]` isn't a machine Nikaia builds for. The machines are: {}.", target, expected)), &"codegen_table"));
    }
    Ok(())
}

pub fn codegen_key(target: &str, key: &str) -> Result<(), nikaia_std::error::Thrown<Refused>> {
    if !contains(&codegen_keys(), key) {
        let expected = joined(&codegen_keys());
        return Err(nikaia_std::error::throwing(Refused::Because(format!("`[build.{}]` has no key called `{}`. The keys are: {}.", target, key, expected)), &"codegen_key"));
    }
    Ok(())
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Shape {
    Rust,
    Path,
    Nikaia,
}

pub fn dependency(name: &str, typed: bool, kind: &str, has_path: bool) -> Result<Shape, nikaia_std::error::Thrown<Refused>> {
    if typed {
        if kind == "rust" { return Ok(Shape::Rust); }
        return Err(nikaia_std::error::throwing(Refused::Because(format!("Dependency `{}` has `type = \"{}\"`, which isn't a kind of dependency Nikaia knows. The only one is `rust`, for a crate from crates.io.", name, kind)), &"dependency"));
    }
    if has_path { return Ok(Shape::Path); }
    Ok(Shape::Nikaia)
}

pub fn crate_name(key: &str) -> String {
    let mut name: String = String::from("");
    for c in key.chars() { if c == '-' { name.push('_'); } else { name.push(c); } }
    name
}

fn contains(words: &[String], word: &str) -> bool {
    for w in words.iter() { if w == word { return true; } }
    false
}

fn joined(words: &[String]) -> String {
    let mut out: String = String::from("");
    for w in words.iter() {
        if (out.len() as i64) > 0 { out.push_str(", "); }
        out.push_str(w);
    }
    out
}

