// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Export {
    pub at: String,
    pub prefix: String,
    pub name: Option<Named>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Named {
    pub name: String,
    pub alias: String,
}

pub fn after(path: &str, word: &str) -> Option<String> {
    if path == word { return Some(String::from("")); }
    let lead = format!("{}::", word);
    if !path.starts_with(&lead) { return None; }
    let c: Vec<char> = nikaia_std::list::chars(path.chars());
    let w: Vec<char> = nikaia_std::list::chars(lead.chars());
    Some(slice(&c, w.len() as i64, c.len() as i64))
}

pub fn module_of(relative: &str) -> Option<String> {
    if !relative.starts_with("src/") || !relative.ends_with(".rs") { return None; }
    let c: Vec<char> = nikaia_std::list::chars(relative.chars());
    let inside = slice(&c, 4, c.len() as i64 - 3);
    if inside == "lib" { return Some(String::from("")); }
    if inside == "main" || inside.starts_with("bin/") { return None; }
    let mut path = inside.to_owned();
    if inside == "mod" { path = String::from(""); } else if inside.ends_with("/mod") {
        let i: Vec<char> = nikaia_std::list::chars(inside.chars());
        path = slice(&i, 0, i.len() as i64 - 4);
    }
    let mut out: String = String::from("");
    for part in path.split("/") { out = joined(&out, part); }
    Some(out)
}

pub fn joined(at: &str, name: &str) -> String {
    if at.is_empty() { return name.to_owned(); }
    if name.is_empty() { return at.to_owned(); }
    format!("{}::{}", at, name)
}

pub fn exported(at: &str, text: &str) -> Vec<Export> {
    let __keep_frame = nikaia_std::tether::Keep::new();
    let whole = text.trim();
    let c: Vec<char> = nikaia_std::list::chars(whole.chars());
    let mut out: Vec<Export> = vec![];
    let open = find_text(&c, 0, "::{");
    if open >= 0 && whole.ends_with("}") {
        let prefix = slice(&c, 0, open);
        let inside = slice(&c, open + 3, c.len() as i64 - 1);
        for one in split_top_level(&inside) { if !one.is_empty() { out.push(Export { at: at.to_owned(), prefix: prefix.to_owned(), name: Some(named(&one)) }); } }
        return out;
    }
    if whole.ends_with("::*") {
        out.push(Export { at: at.to_owned(), prefix: slice(&c, 0, c.len() as i64 - 3), name: None });
        return out;
    }
    let mut path = whole.to_owned();
    let mut alias: Option<String> = None;
    let space = find_text(&c, 0, " as ");
    if space >= 0 {
        let before = __keep_frame.put(slice(&c, 0, space));
        let after_it = __keep_frame.put(slice(&c, space + 4, c.len() as i64));
        path = before.trim().to_owned();
        alias = Some(after_it.trim().to_owned());
    }
    let p: Vec<char> = nikaia_std::list::chars(path.chars());
    let cut = find_last_text(&p, "::");
    let mut prefix: String = String::from("");
    let mut name = path.to_owned();
    if cut >= 0 {
        prefix = slice(&p, 0, cut);
        let rest = __keep_frame.put(slice(&p, cut + 2, p.len() as i64));
        name = rest.trim().to_owned();
    }
    let offered = nikaia_std::index::or(alias, || name.to_owned().into());
    out.push(Export { at: at.to_owned(), prefix, name: Some(Named { name, alias: offered }) });
    out
}

pub fn named(written: &str) -> Named {
    let one = written.trim();
    let c: Vec<char> = nikaia_std::list::chars(one.chars());
    let space = find_text(&c, 0, " as ");
    if space < 0 { return Named { name: one.to_owned(), alias: one.to_owned() }; }
    let before = slice(&c, 0, space);
    let after_it = slice(&c, space + 4, c.len() as i64);
    Named { name: before.trim().to_owned(), alias: after_it.trim().to_owned() }
}

pub fn bases(export: &Export) -> Vec<String> {
    let prefix = export.prefix.trim();
    let mut out: Vec<String> = vec![];
    let from_root = after(prefix, "crate");
    if from_root.is_some() {
        out.push(nikaia_std::index::or(from_root, || "".into()));
        return out;
    }
    let from_here = after(prefix, "self");
    if from_here.is_some() {
        out.push(joined(&export.at, nikaia_std::index::or(from_here.as_deref(), || "")));
        return out;
    }
    let from_up = after(prefix, "super");
    if from_up.is_some() {
        let a: Vec<char> = nikaia_std::list::chars(export.at.chars());
        let cut = find_last_text(&a, "::");
        let mut parent: String = String::from("");
        if cut >= 0 { parent = slice(&a, 0, cut); }
        out.push(joined(&parent, nikaia_std::index::or(from_up.as_deref(), || "")));
        return out;
    }
    let here = joined(&export.at, prefix);
    let root = prefix.to_owned();
    if here != root { out.push(here); }
    out.push(root);
    out
}

pub fn split_top_level(text: &str) -> Vec<String> {
    let __keep_frame = nikaia_std::tether::Keep::new();
    let c: Vec<char> = nikaia_std::list::chars(text.chars());
    let mut out: Vec<String> = vec![];
    let mut depth = 0;
    let mut start: i64 = 0;
    for at in 0..c.len() as i64 {
        let one = *nikaia_std::index::get(&c, nikaia_std::index::at(at));
        if one == '<' || one == '(' || one == '[' { depth += 1; } else if one == '>' || one == ')' || one == ']' { depth -= 1; } else if one == ',' && depth == 0 {
            let piece = __keep_frame.put(slice(&c, start, at));
            out.push(piece.trim().to_owned());
            start = at + 1;
        }
    }
    let last = __keep_frame.put(slice(&c, start, c.len() as i64));
    let rest = last.trim();
    if !rest.is_empty() { out.push(rest.to_owned()); }
    out
}

fn find_text(c: &[char], from: i64, word: &str) -> i64 {
    let w: Vec<char> = nikaia_std::list::chars(word.chars());
    if w.is_empty() || (c.len() as i64) < w.len() as i64 { return -1; }
    for at in from..c.len() as i64 - w.len() as i64 + 1 { if stands_at(c, at, &w) { return at; } }
    -1
}

fn find_last_text(c: &[char], word: &str) -> i64 {
    let w: Vec<char> = nikaia_std::list::chars(word.chars());
    let mut found: i64 = -1;
    if w.is_empty() || (c.len() as i64) < w.len() as i64 { return found; }
    for at in 0..c.len() as i64 - w.len() as i64 + 1 { if stands_at(c, at, &w) { found = at; } }
    found
}

fn stands_at(c: &[char], at: i64, w: &[char]) -> bool {
    for k in 0..w.len() as i64 { if *nikaia_std::index::get(&c, nikaia_std::index::at(at + k)) != *nikaia_std::index::get(&w, nikaia_std::index::at(k)) { return false; } }
    true
}

fn slice(c: &[char], from: i64, to: i64) -> String {
    let mut out: String = String::from("");
    for k in from..to { out.push(*nikaia_std::index::get(&c, nikaia_std::index::at(k))); }
    out
}

