// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


#[allow(unused_imports)]
use nikaia_std::collections;

#[derive(Debug, Clone)]
pub struct Translated {
    pub ty: Ty,
    pub kept: bool,
}

#[derive(Debug, Clone)]
pub struct Resulted {
    pub ty: Ty,
    pub fails: Option<String>,
}

pub fn translate(written: &str, crate_word: &str, parameters: &Vec<String>, types: &collections::BTreeSet<String>, mentioned: &mut collections::BTreeSet<String>) -> Translated {
    let text = written.trim();
    if text.starts_with("&mut ") { return Translated { ty: Ty::Unknown, kept: false }; }
    if text.starts_with("&") {
        let c: Vec<char> = nikaia_std::list::chars(text.chars());
        let rest = slice(&c, 1, c.len() as i64);
        let inner = translate(&rest, crate_word, parameters, types, mentioned);
        return Translated { ty: view_of(inner.ty), kept: false };
    }
    let optional = generic_of(text, "Option");
    if optional.is_some() {
        let inner = translate(nikaia_std::index::or(optional.as_deref(), || ""), crate_word, parameters, types, mentioned);
        return Translated { ty: Ty::Nullable(Box::new(inner.ty)), kept: inner.kept };
    }
    let listed = generic_of(text, "Vec");
    if listed.is_some() {
        let inner = translate(nikaia_std::index::or(listed.as_deref(), || ""), crate_word, parameters, types, mentioned);
        return Translated { ty: Ty::Named { name: String::from("Vec"), args: vec![inner.ty], view: false }, kept: true };
    }
    for parameter in parameters.iter() { if text == parameter { return Translated { ty: Ty::Var { name: text.to_owned(), view: false }, kept: true }; } }
    if is_plain(text) { return Translated { ty: Ty::Named { name: text.to_owned(), args: vec![], view: false }, kept: false }; }
    if text == "String" { return Translated { ty: Ty::Named { name: String::from("String"), args: vec![], view: false }, kept: true }; }
    if types.contains(text) {
        mentioned.insert(text.to_owned());
        return Translated { ty: Ty::Named { name: format!("{}::{}", crate_word, text), args: vec![], view: false }, kept: true };
    }
    Translated { ty: Ty::Unknown, kept: true }
}

pub fn result_of(written: &str, crate_word: &str, parameters: &Vec<String>, types: &collections::BTreeSet<String>, mentioned: &mut collections::BTreeSet<String>) -> Resulted {
    let resulted = generic_of(written, "Result");
    if resulted.is_none() {
        let plain = translate(written, crate_word, parameters, types, mentioned);
        return Resulted { ty: plain.ty, fails: None };
    }
    let parts = split_top_level(nikaia_std::index::or(resulted.as_deref(), || ""));
    let mut ok: String = String::from("");
    if (parts.len() as i64) > 0 { ok = (*nikaia_std::index::get(&parts, 0)).to_owned(); }
    let fine = translate(&ok, crate_word, parameters, types, mentioned);
    let mut fails: String = String::from("?");
    if (parts.len() as i64) > 1 {
        let error = (*nikaia_std::index::get(&parts, 1)).trim();
        if types.contains(error) { fails = format!("{}::{}", crate_word, error); }
    }
    Resulted { ty: fine.ty, fails: Some(fails) }
}

pub fn view_of(ty: Ty) -> Ty {
    match ty {
        Ty::Named { name, args, .. } => Ty::Named { name, args, view: true },
        Ty::Var { name, .. } => Ty::Var { name, view: true },
        _ => ty,
    }
}

pub fn sent_across(names: &Vec<String>, types: &Vec<String>, bounds: &str) -> Vec<String> {
    let sent = sends(bounds);
    let mut out: Vec<String> = vec![];
    for at in 0..names.len() as i64 {
        let ty = (*nikaia_std::index::get(&types, nikaia_std::index::at(at))).trim();
        let named = unreferenced(ty);
        let mut reached = bounds_send(ty);
        for one in sent.iter() { if *one == named { reached = true; } }
        if reached { out.push((*nikaia_std::index::get(&names, nikaia_std::index::at(at))).to_owned()); }
    }
    out
}

pub fn sends(bounds: &str) -> Vec<String> {
    let __keep_frame = nikaia_std::tether::Keep::new();
    let mut out: Vec<String> = vec![];
    for one in split_top_level(bounds) {
        let c: Vec<char> = nikaia_std::list::chars(one.chars());
        let colon = find(&c, ':');
        if colon < 0 { continue; }
        let head = __keep_frame.put(slice(&c, 0, colon));
        let name = head.trim();
        let bound = slice(&c, colon + 1, c.len() as i64);
        if bounds_send(&bound) && !name.is_empty() && !name.starts_with("'") && !out.contains(&name.to_owned()) { out.push(name.to_owned()); }
    }
    out.sort();
    out
}

fn unreferenced(ty: &str) -> String {
    let c: Vec<char> = nikaia_std::list::chars(ty.chars());
    let mut from: i64 = 0;
    while from < c.len() as i64 && (*nikaia_std::index::get(&c, nikaia_std::index::at(from)) == '&' || *nikaia_std::index::get(&c, nikaia_std::index::at(from)) == ' ') { from += 1; }
    let rest = slice(&c, from, c.len() as i64);
    let trimmed = rest.trim();
    if trimmed.starts_with("mut ") {
        let t: Vec<char> = nikaia_std::list::chars(trimmed.chars());
        let after = slice(&t, 4, t.len() as i64);
        return after.to_owned();
    }
    trimmed.to_owned()
}

fn is_plain(name: &str) -> bool {
    for plain in vec!["bool", "char", "str", "i8", "i16", "i32", "i64", "i128", "isize", "u8", "u16", "u32", "u64", "u128", "usize", "f32", "f64", "()"] { if name == plain { return true; } }
    false
}

fn bounds_send(text: &str) -> bool {
    let c: Vec<char> = nikaia_std::list::chars(text.chars());
    let mut start: i64 = 0;
    for at in 0..c.len() as i64 + 1 {
        let ends = at == c.len() as i64 || !((*nikaia_std::index::get(&c, nikaia_std::index::at(at))).is_alphanumeric() || *nikaia_std::index::get(&c, nikaia_std::index::at(at)) == '_');
        if ends {
            if slice(&c, start, at) == "Send" { return true; }
            start = at + 1;
        }
    }
    false
}

fn generic_of(written: &str, name: &str) -> Option<String> {
    let text = written.trim();
    if !text.starts_with(name) { return None; }
    let c: Vec<char> = nikaia_std::list::chars(text.chars());
    let n: Vec<char> = nikaia_std::list::chars(name.chars());
    let after = slice(&c, n.len() as i64, c.len() as i64);
    let rest = after.trim_start();
    if !rest.starts_with("<") || !rest.ends_with(">") { return None; }
    let r: Vec<char> = nikaia_std::list::chars(rest.chars());
    Some(slice(&r, 1, r.len() as i64 - 1))
}

fn split_top_level(text: &str) -> Vec<String> {
    let __keep_frame = nikaia_std::tether::Keep::new();
    let c: Vec<char> = nikaia_std::list::chars(text.chars());
    let mut out: Vec<String> = vec![];
    let mut depth = 0;
    let mut start: i64 = 0;
    for at in 0..c.len() as i64 {
        let one = *nikaia_std::index::get(&c, nikaia_std::index::at(at));
        if one == '<' || one == '(' || one == '[' { depth += 1; } else if one == '>' || one == ')' || one == ']' { depth -= 1; } else if one == ',' && depth == 0 {
            let piece = __keep_frame.put(slice(&c, start, at));
            out.push(piece.trim().to_owned());
            start = at + 1;
        }
    }
    let last = __keep_frame.put(slice(&c, start, c.len() as i64));
    let rest = last.trim();
    if !rest.is_empty() { out.push(rest.to_owned()); }
    out
}

fn find(c: &[char], target: char) -> i64 {
    for at in 0..c.len() as i64 { if *nikaia_std::index::get(&c, nikaia_std::index::at(at)) == target { return at; } }
    -1
}

fn slice(c: &[char], from: i64, to: i64) -> String {
    let mut out: String = String::from("");
    for k in from..to { out.push(*nikaia_std::index::get(&c, nikaia_std::index::at(k))); }
    out
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Written {
    pub names: Vec<String>,
    pub types: Vec<String>,
    pub result: String,
    pub pauses: bool,
    pub parameters: Vec<String>,
}

pub fn contract(written: &Written, crate_word: &str, types: &collections::BTreeSet<String>, mentioned: &mut collections::BTreeSet<String>) -> FnContract {
    let mut keeps: Vec<String> = vec![];
    let mut params: Vec<(String, Ty)> = vec![];
    for at in 0..written.names.len() as i64 {
        let translated = translate(nikaia_std::index::get(&written.types, nikaia_std::index::at(at)), crate_word, &written.parameters, types, mentioned);
        if translated.kept { keeps.push((*nikaia_std::index::get(&written.names, nikaia_std::index::at(at))).to_owned()); }
        params.push(((*nikaia_std::index::get(&written.names, nikaia_std::index::at(at))).to_owned(), translated.ty));
    }
    let mut fails: Vec<String> = vec![];
    let mut answer: Option<Ty> = None;
    if !written.result.is_empty() {
        let resulted = result_of(&written.result, crate_word, &written.parameters, types, mentioned);
        if resulted.fails.is_some() { fails.push(nikaia_std::index::or(resulted.fails, || "?".into())); }
        answer = Some(resulted.ty);
    }
    let mut signature = Signature::empty();
    signature.params = params;
    signature.result = answer;
    let mut entry = FnContract::empty();
    entry.public = true;
    entry.sync_claim = if written.pauses { Sync::No } else { Sync::Asserted };
    entry.fails_with = fails;
    entry.keeps = keeps;
    entry.signature = Some(signature);
    entry
}

