// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

#[allow(unused_imports)]
pub use nikaia_std::error::Full;

#[allow(unused_imports)]
use nikaia_std::fs;

#[allow(unused_imports)]
use nikaia_std::collections;

pub async fn rust_sources(src: &str) -> Result<collections::BTreeMap<String, String>, nikaia_std::error::Thrown<io::IoError>> {
    let mut out = collections::BTreeMap::new();
    for name in fs::walk(src, &fs::Root::Anywhere).await? {
        if !name.ends_with(".rs") { continue; }
        let text = fs::read_to_string(format!("{}/{}", src, name), &fs::Root::Anywhere).await?;
        out.insert(format!("src/{}", name), text);
    }
    Ok(out)
}

