// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
pub fn distance(a: &str, b: &str) -> i64 {
    let x: Vec<char> = nikaia_std::list::chars(a.chars());
    let y: Vec<char> = nikaia_std::list::chars(b.chars());
    let rows = x.len() as i64 + 1;
    let cols = y.len() as i64 + 1;
    let mut d: Vec<Vec<i64>> = Vec::new();
    for i in 0..rows {
        let mut row: Vec<i64> = Vec::new();
        for j in 0..cols { if i == 0 { row.push(j); } else if j == 0 { row.push(i); } else { row.push(0); } }
        d.push(row);
    }
    for i in 1..rows {
        for j in 1..cols {
            let cost = if *nikaia_std::index::get(&x, nikaia_std::index::at(i - 1)) == *nikaia_std::index::get(&y, nikaia_std::index::at(j - 1)) { 0 } else { 1 };
            let mut best = *nikaia_std::index::get(nikaia_std::index::get(&d, nikaia_std::index::at(i - 1)), nikaia_std::index::at(j)) + 1;
            if *nikaia_std::index::get(nikaia_std::index::get(&d, nikaia_std::index::at(i)), nikaia_std::index::at(j - 1)) + 1 < best { best = *nikaia_std::index::get(nikaia_std::index::get(&d, nikaia_std::index::at(i)), nikaia_std::index::at(j - 1)) + 1; }
            if *nikaia_std::index::get(nikaia_std::index::get(&d, nikaia_std::index::at(i - 1)), nikaia_std::index::at(j - 1)) + cost < best { best = *nikaia_std::index::get(nikaia_std::index::get(&d, nikaia_std::index::at(i - 1)), nikaia_std::index::at(j - 1)) + cost; }
            let swapped = i > 1 && j > 1 && *nikaia_std::index::get(&x, nikaia_std::index::at(i - 1)) == *nikaia_std::index::get(&y, nikaia_std::index::at(j - 2)) && *nikaia_std::index::get(&x, nikaia_std::index::at(i - 2)) == *nikaia_std::index::get(&y, nikaia_std::index::at(j - 1));
            if swapped && *nikaia_std::index::get(nikaia_std::index::get(&d, nikaia_std::index::at(i - 2)), nikaia_std::index::at(j - 2)) + 1 < best { best = *nikaia_std::index::get(nikaia_std::index::get(&d, nikaia_std::index::at(i - 2)), nikaia_std::index::at(j - 2)) + 1; }
            { let __nikaia_stored = best; nikaia_std::index::set(&mut d[nikaia_std::index::at(i)], nikaia_std::index::at(j), __nikaia_stored); }
        }
    }
    *nikaia_std::index::get(nikaia_std::index::get(&d, nikaia_std::index::at(rows - 1)), nikaia_std::index::at(cols - 1))
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
pub fn one_edit_apart(a: &str, b: &str) -> bool {
    if a == b { return false; }
    let x: Vec<char> = nikaia_std::list::chars(a.chars());
    let y: Vec<char> = nikaia_std::list::chars(b.chars());
    if (x.len() as i64) == y.len() as i64 {
        let mut differ = 0;
        for i in 0..x.len() as i64 { if *nikaia_std::index::get(&x, nikaia_std::index::at(i)) != *nikaia_std::index::get(&y, nikaia_std::index::at(i)) { differ += 1; } }
        return differ == 1;
    }
    if (x.len() as i64) == y.len() as i64 + 1 { return one_put_in(a, b); }
    if (y.len() as i64) == x.len() as i64 + 1 { return one_put_in(b, a); }
    false
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
fn one_put_in(long: &str, short: &str) -> bool {
    let kept: Vec<char> = nikaia_std::list::chars(short.chars());
    let mut at: i64 = 0;
    let mut skipped = false;
    for c in long.chars() { if at < kept.len() as i64 && *nikaia_std::index::get(&kept, nikaia_std::index::at(at)) == c { at += 1; } else if skipped { return false; } else { skipped = true; } }
    true
}

