// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


#[allow(unused_imports)]
use nikaia_std::collections;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Arg {
    pub name: String,
    pub ty: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Function {
    pub parameters: Vec<String>,
    pub args: Vec<Arg>,
    pub result: String,
    pub bounds: String,
    pub calls: Vec<String>,
    pub pauses: bool,
}

#[derive(Debug, Clone)]
pub struct Surface {
    pub functions: collections::BTreeMap<String, Function>,
    pub offers: collections::BTreeSet<String>,
    pub fields: collections::BTreeMap<String, Vec<String>>,
    pub types: collections::BTreeSet<String>,
    pub derives: collections::BTreeMap<String, collections::BTreeSet<String>>,
    pub modules: collections::BTreeMap<String, bool>,
    pub reachable: collections::BTreeMap<String, String>,
    pub exports: Vec<Export>,
    pub promises: Vec<String>,
}

pub fn empty() -> Surface { Surface { functions: collections::BTreeMap::new(), offers: collections::BTreeSet::new(), fields: collections::BTreeMap::new(), types: collections::BTreeSet::new(), derives: collections::BTreeMap::new(), modules: collections::BTreeMap::new(), reachable: collections::BTreeMap::new(), exports: vec![], promises: vec![] } }

pub fn read(surface: &mut Surface, relative: &str, items: &Vec<Item>) {
    let found = module_of(relative);
    if found.is_none() { return; }
    let at = nikaia_std::index::or(found, || "".into());
    let mut imports: collections::BTreeMap<String, String> = collections::BTreeMap::new();
    imported(items, &mut imports);
    walk(surface, items, &at, &imports);
}

pub fn resolve(surface: &mut Surface) {
    let mut direct: Vec<String> = vec![];
    for path in surface.offers.iter() { if offered(&surface, path) { direct.push(path.to_owned()); } }
    for path in surface.types.iter() { if offered(&surface, path) { direct.push(path.to_owned()); } }
    for path in direct.iter() { surface.reachable.insert(path.to_owned(), path.to_owned()); }
    let mut exports: Vec<Export> = vec![];
    for export in surface.exports.iter() { if offered(&surface, &joined(&export.at, "x")) { exports.push(export.clone()); } }
    for _ in 0..8 {
        let mut added = false;
        for export in exports.iter() {
            if export.name.is_some() {
                let named = nikaia_std::index::or(match export.name.as_ref() {
                    Some(__nikaia_it) => Some(__nikaia_it.clone()),
                    None => None,
                }, || Named { name: String::from(""), alias: String::from("") });
                let offered_as = joined(&export.at, &named.alias);
                for candidate in candidates(export, &named.name) {
                    if surface.functions.contains_key(&candidate) || surface.types.contains(&candidate) {
                        if !surface.reachable.contains_key(&offered_as) {
                            surface.reachable.insert(offered_as.to_owned(), candidate.to_owned());
                            added = true;
                        }
                        break;
                    }
                }
            } else {
                for base in bases(export) {
                    let under = format!("{}::", base);
                    let mut names: Vec<String> = vec![];
                    for path in surface.offers.iter() {
                        let rest = directly_under(path, &under);
                        if rest.is_some() { names.push(nikaia_std::index::or(rest, || "".into())); }
                    }
                    for path in surface.types.iter() {
                        let rest = directly_under(path, &under);
                        if rest.is_some() { names.push(nikaia_std::index::or(rest, || "".into())); }
                    }
                    for name in names.iter() {
                        let offered_as = joined(&export.at, name);
                        if !surface.reachable.contains_key(&offered_as) {
                            surface.reachable.insert(offered_as.to_owned(), format!("{}::{}", base, name));
                            added = true;
                        }
                    }
                }
            }
        }
        if !added { break; }
    }
    surface.exports = exports;
}

pub fn offered(surface: &Surface, path: &str) -> bool {
    let mut parts: Vec<String> = vec![];
    for part in path.split("::") { parts.push(part.to_owned()); }
    let mut at: String = String::from("");
    for k in 0..parts.len() as i64 - 1 {
        at = joined(&at, nikaia_std::index::get(&parts, nikaia_std::index::at(k)));
        let public = nikaia_std::index::or(surface.modules.get(&at), || false);
        if !public { return false; }
    }
    true
}

pub fn candidates(export: &Export, name: &str) -> Vec<String> {
    let mut out: Vec<String> = vec![];
    for base in bases(export) { if base.is_empty() { out.push(name.to_owned()); } else { out.push(format!("{}::{}", base, name)); } }
    out
}

pub fn imported(items: &Vec<Item>, out: &mut collections::BTreeMap<String, String>) {
    for item in items.iter() {
        match item {
            Item::Used(text) => { let text = *text; imports_of(text, out) },
            Item::Export(text) => { let text = *text; imports_of(text, out) },
            Item::Group(g) => imported(&g.items, out),
            _ => { },
        }
    }
}

fn imports_of(text: &str, out: &mut collections::BTreeMap<String, String>) {
    for one in exported("", text) {
        if one.name.is_none() { continue; }
        let named = nikaia_std::index::or(match one.name.as_ref() {
            Some(__nikaia_it) => Some(__nikaia_it.clone()),
            None => None,
        }, || Named { name: String::from(""), alias: String::from("") });
        if one.prefix.is_empty() { out.insert(named.alias.to_owned(), named.name.to_owned()); } else { out.insert(named.alias.to_owned(), format!("{}::{}", one.prefix, named.name)); }
    }
}

fn walk(surface: &mut Surface, items: &Vec<Item>, at: &str, imports: &collections::BTreeMap<String, String>) {
    for item in items.iter() {
        match item {
            Item::Fun(f) => {
                let path = joined(at, f.name);
                surface.offers.insert(path.to_owned());
                surface.functions.insert(path, function_of(f, imports));
            },
            Item::Hidden(f) => { surface.functions.insert(joined(at, f.name), function_of(f, imports)); },
            Item::Rec(r) => {
                let path = joined(at, r.name);
                if r.what == "struct" {
                    let mut types: Vec<String> = vec![];
                    for part in r.parts.iter() { types.push(part.ty.to_owned()); }
                    surface.fields.insert(path.to_owned(), types);
                }
                let mut derived: collections::BTreeSet<String> = collections::BTreeSet::new();
                for list in r.derives.iter() {
                    let list = *list;
                    for written in list.split(",") {
                        let name = last_segment(written.trim());
                        if !name.is_empty() { derived.insert(name); }
                    }
                }
                surface.derives.insert(path.to_owned(), derived);
                surface.types.insert(path);
            },
            Item::Export(text) => {
                let text = *text;
                for one in exported(at, text) { surface.exports.push(one); }
            },
            Item::Used(_) => { },
            Item::Group(g) => {
                if g.what == "mod" {
                    let path = joined(at, g.name);
                    surface.modules.insert(path.to_owned(), g.visible);
                    walk(surface, &g.items, &path, imports);
                } else if g.what == "unsafe impl" && !g.via.is_empty() { surface.promises.push(format!("unsafe impl {} for {}", g.via, g.name)); }
            },
        }
    }
}

fn function_of(f: &Fun<'_>, imports: &collections::BTreeMap<String, String>) -> Function {
    let mut parameters: Vec<String> = vec![];
    for written in split_top_level(f.generics) {
        if written.starts_with("'") { continue; }
        let name = before_colon(&written);
        if !name.is_empty() { parameters.push(name); }
    }
    let mut args: Vec<Arg> = vec![];
    for part in f.parts.iter() { if part.name != "self" { args.push(Arg { name: part.name.to_owned(), ty: part.ty.to_owned() }); } }
    let mut calls: Vec<String> = vec![];
    for call in f.calls.iter() {
        let call = *call;
        let full = imports.get(call);
        if full.is_none() { calls.push(call.to_owned()); } else { calls.push(nikaia_std::index::or(full.as_deref(), || "").to_owned()); }
    }
    Function { parameters, args, result: f.result.to_owned(), bounds: format!("{}, {}", f.generics, f.wheres), calls, pauses: f.pauses }
}

fn directly_under(path: &str, under: &str) -> Option<String> {
    if !path.starts_with(under) { return None; }
    let c: Vec<char> = nikaia_std::list::chars(path.chars());
    let u: Vec<char> = nikaia_std::list::chars(under.chars());
    let rest = between(&c, u.len() as i64, c.len() as i64);
    if rest.contains("::") { return None; }
    Some(rest)
}

fn before_colon(written: &str) -> String {
    let c: Vec<char> = nikaia_std::list::chars(written.chars());
    let mut end = c.len() as i64;
    for at in 0..c.len() as i64 { if *nikaia_std::index::get(&c, nikaia_std::index::at(at)) == ':' && end == c.len() as i64 { end = at; } }
    let head = between(&c, 0, end);
    head.trim().to_owned()
}

fn last_segment(written: &str) -> String {
    let mut last: String = String::from("");
    for part in written.split("::") { last = part.to_owned(); }
    last
}

fn between(c: &[char], from: i64, to: i64) -> String {
    let mut out: String = String::from("");
    for k in from..to { out.push(*nikaia_std::index::get(&c, nikaia_std::index::at(k))); }
    out
}

