// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

#[allow(unused_imports)]
pub use nikaia_std::error::Full;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Position {
    Text,
    QuotedAttribute,
    Url,
    UnquotedAttribute,
    Script,
    Style,
    Comment,
}

impl Position {
    // sync (Part II, 12.1): pure CPU, cannot pause. Checked before
    // this was written - see `contracts::sync`.
    pub fn escapable(&self) -> bool { matches!(self, Position::Text | Position::QuotedAttribute) }
    // sync (Part II, 12.1): pure CPU, cannot pause. Checked before
    // this was written - see `contracts::sync`.
    pub fn why(&self) -> &str {
        match self {
            Position::Url => "a URL needs percent-encoding and a scheme check, not HTML escaping: `javascript:` survives every one of the five characters",
            Position::UnquotedAttribute => "an unquoted attribute value ends at the first blank, so a space in the value starts a new attribute - quote it and the hole is legal",
            Position::Script => "a `<script>` body is JavaScript, where `&lt;` is not `<` and `</script>` inside a string still ends the element",
            Position::Style => "a CSS block needs CSS escaping, which is a different table",
            Position::Comment => "a comment ends at the first `-->`, and escaping does not produce or remove one",
            _ => "",
        }
    }
    // sync (Part II, 12.1): pure CPU, cannot pause. Checked before
    // this was written - see `contracts::sync`.
    pub fn name(&self) -> &str {
        match self {
            Position::Text => "a text node",
            Position::QuotedAttribute => "a quoted attribute value",
            Position::Url => "a URL attribute",
            Position::UnquotedAttribute => "an unquoted attribute value",
            Position::Script => "a `<script>` body",
            Position::Style => "a `<style>` block",
            Position::Comment => "an HTML comment",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Segment {
    Text(String),
    Hole { expr: String, at: Position },
    For { binding: String, collection: String, body: Vec<Segment> },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Refused {
    Because(String),
}

impl Refused {
    fn message(&self) -> String {
        match self {
            Refused::Because(why) => why.to_owned(),
        }
    }
}
impl std::fmt::Display for Refused {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message())
    }
}
impl std::error::Error for Refused {}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
pub fn literal_length(segments: &[Segment]) -> i64 {
    let mut total: i64 = 0;
    for segment in segments.iter() {
        match segment {
            Segment::Text(text) => { total += text.len() as i64; },
            Segment::For { body, .. } => { total += literal_length(body); },
            _ => { },
        }
    }
    total
}

pub fn split(body: &str) -> Result<Vec<Segment>, nikaia_std::error::Thrown<Refused>> {
    let mut splitter = Splitter { c: nikaia_std::list::chars(body.chars()), at: 0, scan: Scan { state: State::Text, tail: vec![], attribute: String::from("") } };
    let segments = splitter.until(false)?;
    if splitter.at < splitter.c.len() as i64 { return Err(nikaia_std::error::throwing(Refused::Because(String::from("`</for>` without a `<for …>` before it")), &"split")); }
    Ok(segments)
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
pub fn illegal(segments: &[Segment]) -> Vec<(String, Position)> {
    let mut found: Vec<(String, Position)> = vec![];
    for segment in segments.iter() {
        match segment {
            Segment::Hole { expr, at } => { if !at.escapable() { found.push((expr.to_owned(), at.clone())); } },
            Segment::For { body, .. } => { for inner in illegal(body) { found.push(inner); } },
            _ => { },
        }
    }
    found
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
pub fn illegal_message(expr: &str, at: &Position) -> String {
    let name = at.name();
    let why = at.why();
    format!("`{{{}}}` is in {}, which this template cannot escape for\n     = {}\n     = every hole is escaped, every time, and a position where that is not enough is an error rather than a promise that quietly does not hold (ADR-017 D1, D3)", expr, name, why)
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Splitter {
    c: Vec<char>,
    at: i64,
    scan: Scan,
}

impl Splitter {
    fn until(&mut self, inside: bool) -> Result<Vec<Segment>, nikaia_std::error::Thrown<Refused>> {
        let mut segments: Vec<Segment> = vec![];
        let mut text: String = String::from("");
        while self.at < self.c.len() as i64 {
            if self.here("</for>") {
                if inside {
                    self.at += 6;
                    if (text.len() as i64) > 0 { segments.push(Segment::Text(text)); }
                    return Ok(segments);
                }
                return Ok(segments);
            }
            if self.here("<for") && self.at + 4 < self.c.len() as i64 && blank(*nikaia_std::index::get(&self.c, nikaia_std::index::at(self.at + 4))) {
                let (binding, collection) = self.loop_header()?;
                if (text.len() as i64) > 0 {
                    segments.push(Segment::Text(text));
                    text = String::from("");
                }
                let body = self.until(true)?;
                segments.push(Segment::For { binding, collection, body });
                continue;
            }
            let c = *nikaia_std::index::get(&self.c, nikaia_std::index::at(self.at));
            let next = self.at + 1 < self.c.len() as i64;
            if c == '{' && next && *nikaia_std::index::get(&self.c, nikaia_std::index::at(self.at + 1)) == '{' {
                text.push('{');
                self.at += 2;
            } else if c == '}' && next && *nikaia_std::index::get(&self.c, nikaia_std::index::at(self.at + 1)) == '}' {
                text.push('}');
                self.at += 2;
            } else if c == '{' {
                let position = self.scan.position();
                let mut close = self.at + 1;
                while close < self.c.len() as i64 && *nikaia_std::index::get(&self.c, nikaia_std::index::at(close)) != '}' { close += 1; }
                if close == self.c.len() as i64 {
                    let at = self.at;
                    return Err(nikaia_std::error::throwing(Refused::Because(format!("unclosed `{{` in the template, at character {}", at)), &"until"));
                }
                let mut expr: String = String::from("");
                for k in self.at + 1..close { expr.push(*nikaia_std::index::get(&self.c, nikaia_std::index::at(k))); }
                if (text.len() as i64) > 0 {
                    segments.push(Segment::Text(text));
                    text = String::from("");
                }
                segments.push(Segment::Hole { expr: expr.trim().to_owned(), at: position });
                self.at = close + 1;
            } else {
                self.scan.feed(c);
                text.push(c);
                self.at += 1;
            }
        }
        if inside { return Err(nikaia_std::error::throwing(Refused::Because(String::from("a `<for …>` in the template is never closed")), &"until")); }
        if (text.len() as i64) > 0 { segments.push(Segment::Text(text)); }
        Ok(segments)
    }
    // sync (Part II, 12.1): pure CPU, cannot pause. Checked before
    // this was written - see `contracts::sync`.
    fn here(&self, word: &str) -> bool {
        let mut k = self.at;
        for w in word.chars() {
            if k >= self.c.len() as i64 || *nikaia_std::index::get(&self.c, nikaia_std::index::at(k)) != w { return false; }
            k += 1;
        }
        true
    }
    fn loop_header(&mut self) -> Result<(String, String), nikaia_std::error::Thrown<Refused>> {
        let mut close = self.at;
        while close < self.c.len() as i64 && *nikaia_std::index::get(&self.c, nikaia_std::index::at(close)) != '>' { close += 1; }
        if close == self.c.len() as i64 { return Err(nikaia_std::error::throwing(Refused::Because(String::from("`<for` in the template is never closed with `>`")), &"loop_header")); }
        let mut header: String = String::from("");
        for k in self.at + 4..close { header.push(*nikaia_std::index::get(&self.c, nikaia_std::index::at(k))); }
        self.at = close + 1;
        let mut words: Vec<String> = vec![];
        for word in header.split_whitespace() { words.push(word.to_owned()); }
        if (words.len() as i64) != 3 || *nikaia_std::index::get(&words, 1) != "in" { return Err(nikaia_std::error::throwing(Refused::Because(format!("a template loop is written `<for name in :collection>`, not `<for{}>`", header)), &"loop_header")); }
        let binding = (*nikaia_std::index::get(&words, 0)).to_owned();
        let written = (*nikaia_std::index::get(&words, 2)).to_owned();
        if !written.starts_with(":") { return Err(nikaia_std::error::throwing(Refused::Because(format!("`{}` is captured from the enclosing scope, so it is written `:{}` - the colon is where the template's names end and the program's begin (ADR-007 D4)", written, written)), &"loop_header")); }
        let mut collection: String = String::from("");
        let mut first = true;
        for ch in written.chars() {
            if !first { collection.push(ch); }
            first = false;
        }
        Ok((binding, collection))
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Scan {
    state: State,
    tail: Vec<char>,
    attribute: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum State {
    Text,
    Tag,
    Equals,
    Quoted(char),
    Unquoted,
    Script,
    Style,
    Comment,
}

impl Scan {
    // sync (Part II, 12.1): pure CPU, cannot pause. Checked before
    // this was written - see `contracts::sync`.
    fn position(&self) -> Position {
        match self.state {
            State::Text => Position::Text,
            State::Script => Position::Script,
            State::Style => Position::Style,
            State::Comment => Position::Comment,
            State::Quoted(_) => quoted(&self.attribute),
            _ => Position::UnquotedAttribute,
        }
    }
    // sync (Part II, 12.1): pure CPU, cannot pause. Checked before
    // this was written - see `contracts::sync`.
    fn ended_with(&self, word: &str) -> bool {
        let tail: String = self.tail.iter().copied().collect();
        tail.ends_with(word)
    }
    // sync (Part II, 12.1): pure CPU, cannot pause. Checked before
    // this was written - see `contracts::sync`.
    fn saw(&self, word: &str) -> bool {
        let tail: String = self.tail.iter().copied().collect();
        tail.contains(word)
    }
    // sync (Part II, 12.1): pure CPU, cannot pause. Checked before
    // this was written - see `contracts::sync`.
    fn feed(&mut self, c: char) {
        self.tail.push(c.to_ascii_lowercase());
        if (self.tail.len() as i64) > 9 {
            let mut kept: Vec<char> = vec![];
            for k in self.tail.len() as i64 - 9..self.tail.len() as i64 { kept.push(*nikaia_std::index::get(&self.tail, nikaia_std::index::at(k))); }
            self.tail = kept;
        }
        match self.state {
            State::Text => {
                if self.ended_with("<!--") { self.state = State::Comment; } else if c == '<' {
                    self.state = State::Tag;
                    self.attribute = String::from("");
                }
            },
            State::Comment => { if self.ended_with("-->") { self.state = State::Text; } },
            State::Quoted(quote) => {
                if c == quote {
                    self.state = State::Tag;
                    self.attribute = String::from("");
                }
            },
            State::Script => { if self.ended_with("</script") { self.state = State::Tag; } },
            State::Style => { if self.ended_with("</style") { self.state = State::Tag; } },
            _ => self.in_a_tag(c),
        }
    }
    // sync (Part II, 12.1): pure CPU, cannot pause. Checked before
    // this was written - see `contracts::sync`.
    fn in_a_tag(&mut self, c: char) {
        let tag = matches!(self.state, State::Tag);
        let equals = matches!(self.state, State::Equals);
        let unquoted = matches!(self.state, State::Unquoted);
        if self.ended_with("<!--") {
            self.state = State::Comment;
            self.attribute = String::from("");
        } else if c == '>' {
            if self.saw("<script") { self.state = State::Script; } else if self.saw("<style") { self.state = State::Style; } else { self.state = State::Text; }
            self.attribute = String::from("");
        } else if c == '=' && tag { self.state = State::Equals; } else if equals { if c == '"' || c == '\'' { self.state = State::Quoted(c); } else if !blank(c) { self.state = State::Unquoted; } } else if unquoted && blank(c) {
            self.state = State::Tag;
            self.attribute = String::from("");
        } else if tag { if blank(c) || c == '<' { self.attribute = String::from(""); } else { self.attribute.push(c.to_ascii_lowercase()); } }
    }
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
fn quoted(attribute: &str) -> Position {
    match attribute {
        "href" => Position::Url,
        "src" => Position::Url,
        "action" => Position::Url,
        "formaction" => Position::Url,
        "data" => Position::Url,
        "poster" => Position::Url,
        "xlink:href" => Position::Url,
        _ => Position::QuotedAttribute,
    }
}

// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
fn blank(c: char) -> bool { c.is_whitespace() }

