// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Wrote {
    Anywhere,
    TheFilesystemRoot,
}

pub fn spelled(wrote: &Wrote) -> String {
    match wrote {
        Wrote::Anywhere => String::from("Anywhere"),
        Wrote::TheFilesystemRoot => String::from("Dir(\"/\") - which is every directory"),
    }
}

pub fn written_root(names: &winnow_grammar::InternerContext, arg: &Expr) -> Option<Wrote> {
    match arg {
        Expr::Path(segments) => if named(names, segments, "Anywhere") { Some(Wrote::Anywhere) } else { None },
        Expr::Call { func, args, .. } => { let func = nikaia_std::boxed::open(func); the_whole_filesystem(names, func, args) },
        _ => None,
    }
}

fn the_whole_filesystem(names: &winnow_grammar::InternerContext, func: &Expr, args: &Vec<Expr>) -> Option<Wrote> {
    let is_dir = match func {
        Expr::Path(segments) => named(names, segments, "Dir"),
        _ => false,
    };
    if !is_dir || (args.len() as i64) == 0 { return None; }
    match *nikaia_std::index::get(&args, 0) {
        Expr::LitStr { ref text, .. } => if text == "/" { Some(Wrote::TheFilesystemRoot) } else { None },
        _ => None,
    }
}

fn named(names: &winnow_grammar::InternerContext, segments: &Vec<winnow_grammar::Symbol>, variant: &str) -> bool {
    let n = segments.len() as i64;
    n >= 2 && names.resolve(*nikaia_std::index::get(&segments, nikaia_std::index::at(n - 2))) == "Root" && names.resolve(*nikaia_std::index::get(&segments, nikaia_std::index::at(n - 1))) == variant
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Reason {
    pub source: String,
    pub untrusted: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Place {
    pub line: i64,
    pub column: i64,
    pub entry: String,
    pub wrote: Wrote,
}

pub fn render(untrusted: bool, reasons: &[Reason], places: &[Place], path: &str) -> String {
    let mut out = format!("input provenance: {}\n", provenance(untrusted));
    if (reasons.len() as i64) == 0 { out.push_str("    no source is read, so nothing entered from outside\n"); }
    for reason in reasons.iter() { out.push_str(&format!("    {} is {}\n", reason.source, provenance(reason.untrusted))); }
    let hash = if untrusted { "keyed, per-process random seed - key choice cannot be aimed at the table" } else { "fast, fixed seed - no adversary chooses these keys" };
    out.push_str(&format!("hash for a map keyed by the input: {}\n", hash));
    out.push_str("file access with no root to check against:\n");
    if (places.len() as i64) == 0 { out.push_str("    none - every path here names a directory it may not leave\n"); }
    for place in places.iter() { out.push_str(&format!("    {}:{}:{}  {} writes {}\n", path, place.line, place.column, place.entry, spelled(&place.wrote))); }
    out
}

fn provenance(untrusted: bool) -> String { if untrusted { String::from("untrusted") } else { String::from("trusted") } }

