// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


#[allow(unused_imports)]
use nikaia_std::text;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Ty {
    Unknown,
    Named { name: String, args: Vec<Ty>, view: bool },
    Tuple(Vec<Ty>),
    Pointed { item: Box<Ty>, slice: bool, mutable: bool },
    Count(i64),
    Var { name: String, view: bool },
    Fn { params: Vec<Ty>, result: Box<Option<Ty>>, is_sync: bool, can_throw: bool },
    Nullable(Box<Ty>),
    Seq { item: Box<Ty>, is_sync: bool, pauses: bool, can_throw: bool, parallel: bool, shape: Shape },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Shape {
    pub ends: bool,
    pub sized: bool,
    pub replays: bool,
}

impl Shape {
    pub fn none() -> Shape { Shape { ends: false, sized: false, replays: false } }
    pub fn meets(&self, wanted: &Shape) -> bool { (self.missing(wanted).len() as i64) == 0 }
    pub fn missing(&self, wanted: &Shape) -> Vec<String> {
        let mut words: Vec<String> = vec![];
        if wanted.ends && !self.ends { words.push(ENDS.to_owned()); }
        if wanted.sized && !self.sized { words.push(SIZED.to_owned()); }
        if wanted.replays && !self.replays { words.push(REPLAYS.to_owned()); }
        words
    }
}

pub const ENDS: &str = "ends";

pub const SIZED: &str = "sized";

pub const REPLAYS: &str = "replays";

pub const SEQ: &str = "Seq";

pub const PAR: &str = "Par";

pub const PAUSES: &str = "pauses";

pub const ARRAY: &str = "Array";

const ARRAY_OPEN: &str = "Array[";

const ARRAY_OPEN_LENGTH: i64 = 6;

pub const TEXT: &str = "String";

pub const TEXT_VIEW: &str = "str";

impl Ty {
    pub fn text(&self) -> String { text(self) }
}

pub fn text(ty: &Ty) -> String {
    match ty {
        Ty::Unknown => String::from("?"),
        Ty::Count(n) => { let n = *n; format!("{}", n) },
        Ty::Pointed { item, slice, mutable } => { let item = nikaia_std::boxed::open(item); let mutable = *mutable; let slice = *slice; pointed(item, slice, mutable) },
        Ty::Tuple(parts) => format!("({})", listed(parts)),
        Ty::Fn { params, result, is_sync, can_throw } => { let result = nikaia_std::boxed::open(result); let can_throw = *can_throw; let is_sync = *is_sync; code(params, (result).as_ref(), is_sync, can_throw) },
        Ty::Var { name, view } => { let view = *view; if view { format!("ref ${}", name) } else { format!("${}", name) } },
        Ty::Nullable(inner) => { let inner = nikaia_std::boxed::open(inner); format!("{}?", text(inner)) },
        Ty::Named { name, args, view } => { let view = *view; named(name, args, view) },
        Ty::Seq { item, is_sync, pauses, can_throw, parallel, shape } => { let item = nikaia_std::boxed::open(item); let can_throw = *can_throw; let is_sync = *is_sync; let parallel = *parallel; let pauses = *pauses; sequence(item, is_sync, pauses, can_throw, parallel, shape) },
    }
}

fn listed(parts: &[Ty]) -> String {
    let mut out: String = String::from("");
    for part in parts.iter() {
        if !out.is_empty() { out.push_str(", "); }
        out.push_str(&text(part));
    }
    out
}

fn pointed(item: &Ty, slice: bool, mutable: bool) -> String {
    let mut out: String = String::from("ref ");
    if mutable { out.push_str("mut "); }
    if !slice {
        out.push_str(&text(item));
        return out;
    }
    let written = match item {
        Ty::Nullable(inner) => { let inner = nikaia_std::boxed::open(inner); format!("{}[{}]?", ARRAY, text(inner)) },
        _ => format!("{}[{}]", ARRAY, text(item)),
    };
    out.push_str(&written);
    out
}

fn code(params: &[Ty], result: Option<&Ty>, is_sync: bool, can_throw: bool) -> String {
    let mut out = format!("fn({})", listed(params));
    if result.is_some() {
        let returned = nikaia_std::index::or(match result {
            Some(__nikaia_it) => Some(__nikaia_it.text()),
            None => None,
        }, || "".into());
        out.push_str(&format!(" -> {}", returned));
    }
    if is_sync { out.push_str(" sync"); }
    if can_throw { out.push_str(" throws"); }
    out
}

fn named(name: &str, args: &[Ty], view: bool) -> String {
    let mut out: String = if view { String::from("ref ") } else { String::from("") };
    if view && name == TEXT_VIEW { out.push_str(TEXT); } else { out.push_str(name); }
    if (args.len() as i64) > 0 { out.push_str(&format!("[{}]", listed(args))); }
    out
}

fn sequence(item: &Ty, is_sync: bool, pauses: bool, can_throw: bool, parallel: bool, shape: &Shape) -> String {
    let word = if parallel { PAR } else { SEQ };
    let mut out = format!("{}[{}]", word, text(item));
    if is_sync { out.push_str(" sync"); }
    if pauses { out.push_str(&format!(" {}", PAUSES)); }
    if can_throw { out.push_str(" throws"); }
    for word in Shape::none().missing(shape) { out.push_str(&format!(" {}", word)); }
    out
}

pub fn parse(written: &str) -> Ty {
    let trimmed = written.trim();
    if (trimmed.len() as i64) == 0 || trimmed == "?" { return Ty::Unknown; }
    let count = text::parse_i64(trimmed);
    if count.is_some() { return Ty::Count(nikaia_std::index::or(count, || 0)); }
    let viewed = a_view_of(trimmed);
    let is_a_view = viewed.is_some();
    let marked: String = nikaia_std::index::or(viewed, || "".into());
    if is_a_view {
        let pointer = pointed_at(&marked);
        if pointer.is_some() { return nikaia_std::index::or(pointer, || Ty::Unknown); }
    }
    if trimmed.ends_with("?") { return Ty::Nullable(Box::new(parse(&cut(trimmed, 0, 1)))); }
    if trimmed.starts_with("(") && trimmed.ends_with(")") { return Ty::Tuple(each(&split_args(&cut(trimmed, 1, 1)))); }
    if trimmed.starts_with("fn(") {
        let code = a_function(trimmed);
        if code.is_some() { return nikaia_std::index::or(code, || Ty::Unknown); }
    }
    let sequence = a_sequence(trimmed, SEQ, false);
    if sequence.is_some() { return nikaia_std::index::or(sequence, || Ty::Unknown); }
    let parallel = a_sequence(trimmed, PAR, true);
    if parallel.is_some() { return nikaia_std::index::or(parallel, || Ty::Unknown); }
    if is_a_view { return a_name(marked.trim(), true); }
    a_name(trimmed, false)
}

pub fn split_args(written: &str) -> Vec<String> {
    let mut parts: Vec<String> = vec![];
    let mut depth = 0;
    let mut current: String = String::from("");
    for c in written.chars() {
        if c == '[' || c == '(' {
            depth += 1;
            current.push(c);
        } else if c == ']' || c == ')' {
            if depth > 0 { depth -= 1; }
            current.push(c);
        } else if c == ',' && depth == 0 {
            parts.push(current.trim().to_owned());
            current = String::from("");
        } else { current.push(c); }
    }
    if (current.trim().len() as i64) > 0 { parts.push(current.trim().to_owned()); }
    parts
}

pub fn a_view_of(written: &str) -> Option<String> {
    if written.starts_with("ref ") {
        let rest = cut(written, 4, 0);
        return Some(rest.trim_start().to_owned());
    }
    if written.starts_with("&") {
        let rest = cut(written, 1, 0);
        return Some(rest.trim_start().to_owned());
    }
    None
}

fn each(parts: &[String]) -> Vec<Ty> {
    let mut read: Vec<Ty> = vec![];
    for part in parts.iter() { read.push(parse(part)); }
    read
}

fn between(c: &[char], from: i64, to: i64) -> String {
    let mut out: String = String::from("");
    for k in from..to { out.push(*nikaia_std::index::get(&c, nikaia_std::index::at(k))); }
    out
}

fn cut(written: &str, front: i64, back: i64) -> String {
    let c: Vec<char> = written.chars().collect::<Vec<_>>();
    between(&c, front, c.len() as i64 - back)
}

fn closing(c: &[char], from: i64, closer: char) -> i64 {
    let mut depth = 0;
    for at in from..c.len() as i64 {
        let ch = *nikaia_std::index::get(&c, nikaia_std::index::at(at));
        if ch == '(' || ch == '[' { depth += 1; } else if ch == closer {
            if depth == 0 { return at; }
            depth -= 1;
        } else if ch == ')' || ch == ']' {
            if depth == 0 { return -1; }
            depth -= 1;
        }
    }
    -1
}

fn word_off(tail: &str, word: &str) -> Option<String> {
    if !tail.ends_with(word) { return None; }
    let c: Vec<char> = tail.chars().collect::<Vec<_>>();
    let w: Vec<char> = word.chars().collect::<Vec<_>>();
    let shorter = between(&c, 0, c.len() as i64 - w.len() as i64);
    if (shorter.len() as i64) == 0 { return Some(shorter); }
    if (*nikaia_std::index::get(&c, nikaia_std::index::at(c.len() as i64 - w.len() as i64 - 1))).is_whitespace() { return Some(shorter.trim_end().to_owned()); }
    None
}

fn pointed_at(viewed: &str) -> Option<Ty> {
    let __keep_frame = nikaia_std::tether::Keep::new();
    let mut rest: String = viewed.to_owned();
    let mut mutable = false;
    if rest.starts_with("mut ") {
        mutable = true;
        let shorter = __keep_frame.put(cut(&rest, 4, 0));
        rest = shorter.trim_start().to_owned();
    }
    let mut absent = false;
    if rest.ends_with("?") {
        absent = true;
        let shorter = __keep_frame.put(cut(&rest, 0, 1));
        rest = shorter.trim_end().to_owned();
    }
    let mut slice = false;
    let mut inner: String = String::from("");
    if rest.starts_with(ARRAY_OPEN) && rest.ends_with("]") {
        let args = cut(&rest, ARRAY_OPEN_LENGTH, 1);
        if (split_args(&args).len() as i64) == 1 {
            slice = true;
            inner = args;
        }
    }
    if !slice && rest.starts_with("[") && rest.ends_with("]") {
        slice = true;
        inner = cut(&rest, 1, 1);
    }
    if !mutable && !slice { return None; }
    if !slice { inner = rest.to_owned(); }
    let item = parse(&inner);
    if absent { return Some(Ty::Pointed { item: Box::new(Ty::Nullable(Box::new(item))), slice, mutable }); }
    Some(Ty::Pointed { item: Box::new(item), slice, mutable })
}

fn a_function(written: &str) -> Option<Ty> {
    let c: Vec<char> = written.chars().collect::<Vec<_>>();
    let close = closing(&c, 3, ')');
    if close < 0 { return None; }
    let after = between(&c, close + 1, c.len() as i64);
    let mut tail: String = after.trim().to_owned();
    let mut is_sync = false;
    let mut can_throw = false;
    while (tail.len() as i64) > 0 {
        let without_throws = word_off(&tail, "throws");
        if without_throws.is_some() {
            can_throw = true;
            tail = nikaia_std::index::or(without_throws, || "".into());
            continue;
        }
        let without_sync = word_off(&tail, "sync");
        if without_sync.is_some() {
            is_sync = true;
            tail = nikaia_std::index::or(without_sync, || "".into());
            continue;
        }
        break;
    }
    let params = each(&split_args(&between(&c, 3, close)));
    if tail.starts_with("->") {
        let result = parse(&cut(&tail, 2, 0));
        return Some(Ty::Fn { params, result: Box::new(Some(result)), is_sync, can_throw });
    }
    Some(Ty::Fn { params, result: Box::new(None), is_sync, can_throw })
}

fn a_sequence(written: &str, word: &str, parallel: bool) -> Option<Ty> {
    if !written.starts_with(word) { return None; }
    let w: Vec<char> = word.chars().collect::<Vec<_>>();
    let after_word = cut(written, w.len() as i64, 0);
    let rest: String = after_word.trim_start().to_owned();
    if !rest.starts_with("[") { return None; }
    let c: Vec<char> = rest.chars().collect::<Vec<_>>();
    let close = closing(&c, 1, ']');
    if close < 0 { return None; }
    let after = between(&c, close + 1, c.len() as i64);
    let mut tail: String = after.trim().to_owned();
    let mut is_sync = false;
    let mut pauses = false;
    let mut can_throw = false;
    let mut ends = false;
    let mut sized = false;
    let mut replays = false;
    while (tail.len() as i64) > 0 {
        let without_ends = word_off(&tail, ENDS);
        if without_ends.is_some() {
            ends = true;
            tail = nikaia_std::index::or(without_ends, || "".into());
            continue;
        }
        let without_sized = word_off(&tail, SIZED);
        if without_sized.is_some() {
            sized = true;
            tail = nikaia_std::index::or(without_sized, || "".into());
            continue;
        }
        let without_replays = word_off(&tail, REPLAYS);
        if without_replays.is_some() {
            replays = true;
            tail = nikaia_std::index::or(without_replays, || "".into());
            continue;
        }
        let without_throws = word_off(&tail, "throws");
        if without_throws.is_some() {
            can_throw = true;
            tail = nikaia_std::index::or(without_throws, || "".into());
            continue;
        }
        let without_sync = word_off(&tail, "sync");
        if without_sync.is_some() {
            is_sync = true;
            tail = nikaia_std::index::or(without_sync, || "".into());
            continue;
        }
        let without_pauses = word_off(&tail, PAUSES);
        if without_pauses.is_some() {
            pauses = true;
            tail = nikaia_std::index::or(without_pauses, || "".into());
            continue;
        }
        break;
    }
    if is_sync && pauses { return None; }
    if (tail.len() as i64) > 0 { return None; }
    let item = parse(&between(&c, 1, close));
    let shape = Shape { ends, sized, replays };
    Some(Ty::Seq { item: Box::new(item), is_sync, pauses, can_throw, parallel, shape })
}

fn a_name(rest: &str, view: bool) -> Ty {
    if rest.starts_with("$") && (rest.len() as i64) > 1 { return Ty::Var { name: cut(rest, 1, 0), view }; }
    if view && rest == TEXT { return Ty::Named { name: TEXT_VIEW.to_owned(), args: vec![], view: true }; }
    if !rest.ends_with("]") { return Ty::Named { name: rest.to_owned(), args: vec![], view }; }
    let c: Vec<char> = rest.chars().collect::<Vec<_>>();
    let mut open: i64 = -1;
    for at in 0..c.len() as i64 { if open < 0 && *nikaia_std::index::get(&c, nikaia_std::index::at(at)) == '[' { open = at; } }
    if open >= 0 {
        let named = between(&c, 0, open);
        return Ty::Named { name: named.trim().to_owned(), args: each(&split_args(&between(&c, open + 1, c.len() as i64 - 1))), view };
    }
    Ty::Named { name: rest.to_owned(), args: vec![], view }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Provenance {
    Trusted,
    Untrusted,
}

impl Provenance {
    pub fn join(self, other: Provenance) -> Provenance {
        if self == Provenance::Untrusted || other == Provenance::Untrusted { return Provenance::Untrusted; }
        Provenance::Trusted
    }
    pub fn as_str(self) -> String {
        match self {
            Provenance::Trusted => String::from("trusted"),
            Provenance::Untrusted => String::from("untrusted"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Sync {
    No,
    Inferred,
    Asserted,
    From(String),
}

impl Sync {
    pub fn is_sync(&self) -> bool { !matches!(self, Sync::No) }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Lock {
    No,
    Holds,
    Undecided,
}

impl Lock {
    pub fn holds(self) -> bool { self == Lock::Holds }
    pub fn or(self, other: Lock) -> Lock {
        if self == Lock::Holds || other == Lock::Holds { return Lock::Holds; }
        if self == Lock::Undecided || other == Lock::Undecided { return Lock::Undecided; }
        Lock::No
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Crosses {
    May,
    MayNot,
    Undecided,
}

impl Crosses {
    pub fn may(self) -> bool { self == Crosses::May }
    pub fn may_not(self) -> bool { self == Crosses::MayNot }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Threads {
    May,
    MayNot,
    Undecided,
}

impl Threads {
    pub fn may(self) -> bool { self == Threads::May }
    pub fn may_not(self) -> bool { self == Threads::MayNot }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Touch {
    pub kind: String,
    pub parameter: Option<String>,
    pub write: bool,
}

impl Touch {
    pub fn names_a_lock(&self) -> bool { self.kind == "lock" }
    pub fn text(&self) -> String { touched(&self.kind, (self.parameter).as_deref(), self.write) }
}

fn touched(kind: &str, parameter: Option<&str>, write: bool) -> String {
    let access = if write { "write" } else { "read" };
    if parameter.is_none() { return format!("{} {}", kind, access); }
    let named = nikaia_std::index::or(parameter, || "");
    format!("{}({}) {}", kind, named, access)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum State {
    Borrowed,
    Tethered,
}

impl State {
    pub fn as_str(self) -> String {
        match self {
            State::Borrowed => String::from("borrowed"),
            State::Tethered => String::from("tethered"),
        }
    }
    pub fn parse(written: &str) -> Option<State> {
        let word = written.trim();
        if word == "borrowed" { return Some(State::Borrowed); }
        if word == "tethered" { return Some(State::Tethered); }
        None
    }
    pub fn or(self, other: State) -> State {
        if self == State::Tethered || other == State::Tethered { return State::Tethered; }
        State::Borrowed
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Held {
    pub position: String,
    pub state: State,
}

impl Held {
    pub fn text(&self) -> String { format!("{}: {}", self.position, self.state.as_str()) }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Count {
    Plain,
    Word,
    Atomic,
}

impl Count {
    pub fn join(self, other: Count) -> Count {
        if self == Count::Atomic || other == Count::Atomic { return Count::Atomic; }
        if self == Count::Word || other == Count::Word { return Count::Word; }
        Count::Plain
    }
    pub fn rank(self) -> i64 {
        match self {
            Count::Plain => 0,
            Count::Word => 1,
            Count::Atomic => 2,
        }
    }
    pub fn as_str(self) -> String {
        match self {
            Count::Plain => String::from("plain"),
            Count::Word => String::from("word"),
            Count::Atomic => String::from("atomic"),
        }
    }
    pub fn parse(written: &str) -> Option<Count> {
        let word = written.trim();
        if word == "plain" { return Some(Count::Plain); }
        if word == "word" { return Some(Count::Word); }
        if word == "atomic" { return Some(Count::Atomic); }
        None
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Class {
    pub members: Vec<String>,
    pub count: Count,
}

impl Class {
    pub fn text(&self) -> String {
        let mut out: String = String::from("");
        for member in self.members.iter() {
            if !out.is_empty() { out.push_str(" | "); }
            out.push_str(member);
        }
        format!("{}: {}", out, self.count.as_str())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FieldContract {
    pub name: String,
    pub ty: Ty,
    pub public: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VariantContract {
    pub name: String,
    pub holds: Vec<FieldContract>,
    pub positional: bool,
}

impl VariantContract {
    pub fn text(&self) -> String {
        if (self.holds.len() as i64) == 0 { return self.name.to_owned(); }
        let mut parts: String = String::from("");
        for field in self.holds.iter() {
            if !parts.is_empty() { parts.push_str(", "); }
            if self.positional { parts.push_str(&field.ty.text()); } else { parts.push_str(&format!("{}: {}", field.name, field.ty.text())); }
        }
        if self.positional { return format!("{}({})", self.name, parts); }
        format!("{} {{ {} }}", self.name, parts)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConfigContract {
    pub name: String,
    pub ty: Ty,
    pub default: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Signature {
    pub bounds: Vec<(String, Vec<String>)>,
    pub params: Vec<(String, Ty)>,
    pub mutable: Vec<String>,
    pub config: Vec<ConfigContract>,
    pub result: Option<Ty>,
}

impl Signature {
    pub fn empty() -> Signature { Signature { bounds: vec![], params: vec![], mutable: vec![], config: vec![], result: None } }
    pub fn takes_a_receiver(&self) -> bool { (self.params.len() as i64) > 0 && nikaia_std::index::get(&self.params, 0).0 == "self" }
    pub fn result_or_unit(&self) -> Ty {
        nikaia_std::index::or(match self.result.as_ref() {
            Some(__nikaia_it) => Some(__nikaia_it.clone()),
            None => None,
        }, || Ty::Tuple(vec![]))
    }
    pub fn text(&self) -> String {
        let mut inside: String = String::from("");
        for (name, ty) in self.params.iter() {
            if !inside.is_empty() { inside.push_str(", "); }
            if name == "self" { inside.push_str(&ty.text()); } else {
                if self.mutable.contains(name) { inside.push_str("mut "); }
                inside.push_str(&format!("{}: {}", name, ty.text()));
            }
        }
        if (self.config.len() as i64) > 0 {
            inside.push_str("; ");
            let mut first = true;
            for option in self.config.iter() {
                if !first { inside.push_str(", "); }
                first = false;
                inside.push_str(&format!("{}: {} = {}", option.name, option.ty.text(), option.default));
            }
        }
        let mut before: String = String::from("");
        if (self.bounds.len() as i64) > 0 {
            before.push('[');
            let mut first = true;
            for (name, traits) in self.bounds.iter() {
                if !first { before.push_str(", "); }
                first = false;
                before.push_str(name);
                if (traits.len() as i64) > 0 {
                    before.push_str(": ");
                    let mut one = true;
                    for bound in traits.iter() {
                        if !one { before.push_str(" + "); }
                        one = false;
                        before.push_str(bound);
                    }
                }
            }
            before.push(']');
        }
        if self.result.is_none() { return format!("{}({})", before, inside); }
        format!("{}({}) -> {}", before, inside, self.result_or_unit().text())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FnContract {
    pub public: bool,
    pub sync_claim: Sync,
    pub fails_with: Vec<String>,
    pub touches: Vec<Touch>,
    pub touches_known: bool,
    pub provenance: Option<Provenance>,
    pub signature: Option<Signature>,
    pub borrows: Vec<String>,
    pub keeps: Vec<String>,
    pub mutates: bool,
    pub touches_a_lock: Lock,
    pub threads: Threads,
    pub views: Vec<Held>,
    pub sharing: Vec<Class>,
    pub ends_by_length: bool,
}

impl FnContract {
    pub fn empty() -> FnContract { FnContract { public: false, sync_claim: Sync::No, fails_with: vec![], touches: vec![], touches_known: false, provenance: None, signature: None, borrows: vec![], keeps: vec![], mutates: false, touches_a_lock: Lock::No, threads: Threads::Undecided, views: vec![], sharing: vec![], ends_by_length: false } }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TypeContract {
    pub public: bool,
    pub fields: Vec<FieldContract>,
    pub variants: Vec<VariantContract>,
    pub crosses: Crosses,
    pub iterates_fallibly: bool,
    pub compares: bool,
    pub copies: bool,
    pub touches: Vec<String>,
    pub tethered: Vec<String>,
}

impl TypeContract {
    pub fn empty() -> TypeContract { TypeContract { public: false, fields: vec![], variants: vec![], crosses: Crosses::Undecided, iterates_fallibly: false, compares: false, copies: false, touches: vec![], tethered: vec![] } }
}

