// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Ty {
    Unknown,
    Named { name: String, args: Vec<Ty>, view: bool },
    Tuple(Vec<Ty>),
    Pointed { item: Box<Ty>, slice: bool, mutable: bool },
    Count(i64),
    Var { name: String, view: bool },
    Fn { params: Vec<Ty>, result: Box<Option<Ty>>, is_sync: bool, can_throw: bool },
    Nullable(Box<Ty>),
    Seq { item: Box<Ty>, is_sync: bool, pauses: bool, can_throw: bool, parallel: bool, shape: Shape },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Shape {
    pub ends: bool,
    pub sized: bool,
    pub replays: bool,
}

impl Shape {
    pub fn none() -> Shape { Shape { ends: false, sized: false, replays: false } }
    pub fn meets(&self, wanted: &Shape) -> bool { (self.missing(wanted).len() as i64) == 0 }
    pub fn missing(&self, wanted: &Shape) -> Vec<String> {
        let mut words: Vec<String> = vec![];
        if wanted.ends && !self.ends { words.push(format!("{}", ENDS)); }
        if wanted.sized && !self.sized { words.push(format!("{}", SIZED)); }
        if wanted.replays && !self.replays { words.push(format!("{}", REPLAYS)); }
        words
    }
}

pub const ENDS: &str = "ends";

pub const SIZED: &str = "sized";

pub const REPLAYS: &str = "replays";

pub const SEQ: &str = "Seq";

pub const PAR: &str = "Par";

pub const PAUSES: &str = "pauses";

pub const ARRAY: &str = "Array";

pub const TEXT: &str = "String";

pub const TEXT_VIEW: &str = "str";

impl Ty {
    pub fn text(&self) -> String { text(self) }
}

pub fn text(ty: &Ty) -> String {
    match ty {
        Ty::Unknown => String::from("?"),
        Ty::Count(n) => { let n = *n; format!("{}", n) },
        Ty::Pointed { item, slice, mutable } => { let item = nikaia_std::boxed::open(item); let mutable = *mutable; let slice = *slice; pointed(item, slice, mutable) },
        Ty::Tuple(parts) => format!("({})", listed(parts)),
        Ty::Fn { params, result, is_sync, can_throw } => { let result = nikaia_std::boxed::open(result); let can_throw = *can_throw; let is_sync = *is_sync; code(params, (result).as_ref(), is_sync, can_throw) },
        Ty::Var { name, view } => { let view = *view; if view { format!("ref ${}", name) } else { format!("${}", name) } },
        Ty::Nullable(inner) => { let inner = nikaia_std::boxed::open(inner); format!("{}?", text(inner)) },
        Ty::Named { name, args, view } => { let view = *view; named(name, args, view) },
        Ty::Seq { item, is_sync, pauses, can_throw, parallel, shape } => { let item = nikaia_std::boxed::open(item); let can_throw = *can_throw; let is_sync = *is_sync; let parallel = *parallel; let pauses = *pauses; sequence(item, is_sync, pauses, can_throw, parallel, shape) },
    }
}

fn listed(parts: &Vec<Ty>) -> String {
    let mut out: String = String::from("");
    for part in parts.iter() {
        if !out.is_empty() { out.push_str(", "); }
        out.push_str(&text(part));
    }
    out
}

fn pointed(item: &Ty, slice: bool, mutable: bool) -> String {
    let mut out: String = String::from("ref ");
    if mutable { out.push_str("mut "); }
    if !slice {
        out.push_str(&text(item));
        return out;
    }
    let written = match item {
        Ty::Nullable(inner) => { let inner = nikaia_std::boxed::open(inner); format!("{}[{}]?", ARRAY, text(inner)) },
        _ => format!("{}[{}]", ARRAY, text(item)),
    };
    out.push_str(&written);
    out
}

fn code(params: &Vec<Ty>, result: Option<&Ty>, is_sync: bool, can_throw: bool) -> String {
    let mut out = format!("fn({})", listed(params));
    if result.is_some() {
        let returned = nikaia_std::index::or(match result {
            Some(__nikaia_it) => Some(__nikaia_it.text()),
            None => None,
        }, || "".into());
        out.push_str(&format!(" -> {}", returned));
    }
    if is_sync { out.push_str(" sync"); }
    if can_throw { out.push_str(" throws"); }
    out
}

fn named(name: &str, args: &Vec<Ty>, view: bool) -> String {
    let mut out: String = if view { String::from("ref ") } else { String::from("") };
    if view && name == TEXT_VIEW { out.push_str(TEXT); } else { out.push_str(name); }
    if (args.len() as i64) > 0 { out.push_str(&format!("[{}]", listed(args))); }
    out
}

fn sequence(item: &Ty, is_sync: bool, pauses: bool, can_throw: bool, parallel: bool, shape: &Shape) -> String {
    let word = if parallel { PAR } else { SEQ };
    let mut out = format!("{}[{}]", word, text(item));
    if is_sync { out.push_str(" sync"); }
    if pauses { out.push_str(&format!(" {}", PAUSES)); }
    if can_throw { out.push_str(" throws"); }
    for word in Shape::none().missing(shape) { out.push_str(&format!(" {}", word)); }
    out
}

